### ISSUE TITLE
No bin folder present in CEDev

### ISSUE THREAD

**Issue by elfprince13** [CE-Programming/toolchain#1]
The instructions make reference to a non-existent bin folder.

**Comment by adriweb** [comment]
The instructions say to download the _release_, not clone the repo (which doesn't have binaries) ;)

**Comment by elfprince13** [comment]
It should be possible to create the release from the source code zip present on the release page, otherwise it's not "the release source code" ;)

**Comment by MateoConLechuga** [comment]
No it shouldn't be. There is no source.
