### ISSUE TITLE
Adding libraries

### ISSUE THREAD

**Issue by chocol4te** [CE-Programming/toolchain#101]
I am trying to use the GNU Scientific Library in my project, how can I include "/usr/local/include" in my search path?

Thanks! :)

**Comment by adriweb** [comment]
This is absolutely not possible, sorry ;)
(The compiler we use for now only “works” with C89 and the calculator doesn’t have a good enough hardware (it’d need more RAM at the very least) for these kinds of libs.

For a more general answer, you can add the include path inside the core makefile where there are others. But your system’s probably wouldn’t work in this context anyway

**Comment by chocol4te** [comment]
Thanks for your help!

**Comment by chocol4te** [comment]
For future reference, I found the LINPACK and associated libraries to function perfectly for what I needed to do.

**Comment by adriweb** [comment]
Alright, don't hesitate to share your programs when they're ready then :)

**Comment by chocol4te** [comment]
Will do! :)
