### ISSUE TITLE
Update Zilog tools to latest version

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/toolchain#103]
Yes, for some odd reason, it looks like Zilog resumed eZ80 support, and we use 5.2.x here, while 5.3.x got released this year, with bugfixes and improvements...
We should probably use that, I guess it wouldn't hurt!

Edit: it's available here: https://www.zilog.com/index.php?option=com_zcm&task=view&soft_id=23&Itemid=74

**Comment by adriweb** [comment]
It turns out that 5.3.0 is quite buggy... making it actually unsuitable.

**Linker**:
* ⚠️ We have segments range issues (particularly for the BSS, which started at `$D00000` instead of its defined start, even when hardcoded). Might be related to _CR 13377 "When padding bytes with 0xFF, omit padding address ranges that aren't included in the Linker > Address Spaces listing."_
This was caught by several automated tests on Travis.

**Compiler**:
* ⚠️ Some changes to supposedly make the assembly more readable (CR 13376) are actually making it worse. For instance `ld a,(ix+%ffffffff)` in 5.3 instead of `ld a,(ix+-1)` in 5.2.
* 🚫 Wrong code generation for very simple cases: `char test() { char x = 5; return 10-x - 1 + 1; }` returns `5` (as expected) in 5.2, but `-5` in 5.3 (`_test: ld a,%fb \ ret`)
Surprisingly enough, this was not caught by automated tests, but manually.

***
This will be reported to Zilog and hopefully there will be a fix, but in the meantime, we'll have to at least rollback the compiler to 5.2.x.

**Comment by adriweb** [comment]
Reopening that to remind us we need to report that and try their update when/if it comes out, fixing all this.

**Comment by mateoconlechuga** [comment]
Email received from Zilog:

> Hi Matt,
We were able to verify all your compiler issues. 
Regarding your assembler and linker issues, we would need your sample project to debug further.
Let’s continue this ticket discussion inside our Tech Support Platform.  Kindly register below.
https://www.zilog.com/index.php?option=com_product&task=tech_support&Itemid=88

**Comment by mateoconlechuga** [comment]
I haven't heard anything from them sadly :( I'm going to close this until we see another release.

**Comment by adriweb** [comment]
Hey look, a new version, 5.3.3, has appeared (build from late August actually). Let's try the compiler bugs...

**Comment by adriweb** [comment]
Nope, still broken -_-"

![](https://i.imgur.com/kBtgaX9.png)

**Comment by adriweb** [comment]
I wonder what they changed in their latest 5.3.4 release (from late 2019, I just checked now out of curiosity) but they mention "A rare but critical compiler bug, CR 13572, has been fixed."
Not that we care anymore, but maybe it fixes that issue above :P
