### ISSUE TITLE
ti_RclVar() Failing

### ISSUE THREAD

**Issue by chocol4te** [CE-Programming/toolchain#104]
I am having difficulties with the ti_RclVar() function; it will not get any variables, of any type, on CEmu and on a real device, returning a pointer not 0. It fails on the fileio_factorize program too. I don't understand the sequence of instructions on the debugger, and I just wanted to know if it is a problem for me, or everyone.

Thanks!

**Comment by PeterTillema** [comment]
When looking at the README of the `fileio_factorize` program, it takes a real number as Ans and outputs the factors in a list. What did you try? `9:prgmDEMO` correctly returns `{3,3}` for me.

**Comment by chocol4te** [comment]
Hold on, I'll get a screenshot. :)

**Comment by chocol4te** [comment]
My apologies, I was wrong, it is functioning correctly. I'm very sorry to waste your time.

**Comment by chocol4te** [comment]
The function is now only working for me when I use TI_REAL_TYPE, even when the actual type is TI_REAL_LIST_TYPE.
