### ISSUE TITLE
Prompting for input

### ISSUE THREAD

**Issue by AlexGustafsson** [CE-Programming/toolchain#105]
How does one use the builtin (or similar) `Prompt` function? That is, how does one ask the user to enter a number?

I'm aware that I can read a named variable such as `Ans`, but what if I want to ask for multiple numbers similar to a BASIC program?

**Comment by AlexGustafsson** [comment]
Also, is there any way to use the builtin `Disp` function to display a message on the next line? Using the demoed functions to print simply writes the output to a specific line and misses the scrolling behavior of `Disp`.

**Comment by mateoconlechuga** [comment]
I would use the correct language for what you are working with. BASIC is for working within the OS data structures. C is open to the hardware capabilities. I'm not sure what you are trying to accomplish; perhaps more of an idea on what you are trying to create?

**Comment by AlexGustafsson** [comment]
I must've misunderstood the meaning of builtin in this case. From what I could find, there are a lot of functions such as os_xxxx and ti_xxxx with all sorts of access to variables and the like. I figured that those were merely implementations of the already existing functions on the calculator itself.

Though BASIC would probably much simplify the process of entering and representing input, it would be a pain to achieve what I'm implementing.

The only relevant thing here is that i want to:

Ask the user for a number like so (> output, < input);
```
> What is N?
< 2017
```

Though the use of `Ans` could work (as seen in demos) I would like to read multiple variables and not be limited to the user typing in the values to variables beforehand.

Thank you for your time.

**Comment by mateoconlechuga** [comment]
Okay, I can write an assembly snippet that would be able to do this. Just give me a few hours; and then I can release a new toolchain version :)

**Comment by adriweb** [comment]
Well, technically, if you're OK with a console-like environment for this specific thing, [nio_ce](https://github.com/adriweb/nspire-io/) (nspire-io port for the CE) is probably an answer to this.

Example of something made with it:
![RPNcalc](https://tiplanet.org/forum/images/forum_uploads/1381_1507477401_59da47992ca84.gif)

**Comment by mateoconlechuga** [comment]
I would rather it to be accessible from the OS itself :)

**Comment by adriweb** [comment]
Sure, it all depends what the program is anyway :P

**Comment by AlexGustafsson** [comment]
@mateoconlechuga That would be utterly amazing! If you have the time, feel free to comment a bit about how you went about to implement it. It would be an interesting read for sure!

@adriweb Thank you for the suggestion, but as @mateoconlechuga said, it would be nice to have from the OS.

**Comment by runer112** [comment]
Why not do this in TI-BASIC? It's fully capable of taking interactive input, and it's much simpler to do so than in C or assembly.

**Comment by mateoconlechuga** [comment]
A new release has been issued that you can download [here](https://github.com/CE-Programming/toolchain/releases/latest). The key function is `os_GetStringInput()`, which is documented in `tice.h` and has an example program under the name `os_input`.

The custom assembly implementation is available for viewing [here](https://github.com/CE-Programming/toolchain/blob/master/src/ce/getstringinput.src).

Thanks! Let us know if you have any more questions :)

**Comment by mateoconlechuga** [comment]
Sorry about that if you tried to build on Windows and it wasn't working. The release has since been fixed.

**Comment by AlexGustafsson** [comment]
@mateoconlechuga Fortunately I was on a MacBook. Your work did wonders! The change makes the toolkit much more usable for mathematical solutions where the input is usually numeric. I succeeded in implementing Fermats factorisation and the Euclidean algorithm for determining GCD and a linear combination of said GCD with ease. The missing piece was simply the prompt, which you solved. I can’t thank you enough!
