### ISSUE TITLE
Weird results when using the pow() function: 3^1 = 2

### ISSUE THREAD

**Issue by AlexGustafsson** [CE-Programming/toolchain#107]
Faulty code example:

```c
uint24_t a = 3;
uint24_t b = 1;
uint24_t c = pow(a, b);
/* c is 2, not 3 */
```

The fix is simply,
```c
uint24_t a = 3;
uint24_t b = 1;
uint24_t c = ceil(pow(a, b));
/* c is 3 */
```

I'd somewhat understand the issue if I was trying to do this with huge numbers that may result in loss of precision, but for something simple as this... I'm not entirely sure of the inner workings of the pow-function but I do know that it and all other math functions seem to use doubles. I'm guessing that the double math results in some loss in precision when converted to integers.

Is it supposed to be this way and I'm to blame for not using doubles throughout?

**Comment by AlexGustafsson** [comment]
Well, while `ceil(pow(a, b))` did work for some numbers, it makes `ceil(pow(3, 2))` equal to 10, not 9 - so there seem to be an actual issue here.

**Comment by jacobly0** [comment]
This is not a bug, indeed if you do `Math.floor(1*Math.exp(Math.log(3)))` in another language, which is how pow is implemented on the CE, then you will also get 2.  Note that in other toolchains pow special cases integer exponents and so can sometimes return more accurate results.

**Comment by AlexGustafsson** [comment]
Thank you, @jacobly0, for clearing that up!

**Comment by jacobly0** [comment]
The solution to this is very much dependent on the problem.  If you actually want to compute the power of integers, use an integer exponentiation algorithm, if you want to interpret a floating point number as an integer, don't expect casting which is just a glorified floor to not be affected by rounding errors.
