### ISSUE TITLE
Formatting / printing uint32_t numbers result in weird text

### ISSUE THREAD

**Issue by AlexGustafsson** [CE-Programming/toolchain#108]
Trying to debug the calculations I've made in a program, I've faced a problem with `sprintf` and `dbg_sprintf` (which I imagine use the same format implementation). 

The problem is probably best described through code:

```c
uint32_t a = 2612;
uint32_t b = 2;
uint32_t result = ipow(a, b);
uint32_t expected = 6822544;

if (result == expected)
  dbg_sprintf(dbgout, "result is 6 822 544");
else
   dbg_sprintf(dbgout, "result is not 6 822 544");

dbg_sprintf(dbgout, "result is %u", result);
```

Which will print:
```
> result is 6 822 544
> result is 6 815 744
```

__Note: `ipow` here is a verified-to-work function for calculating integer powers.__

Usually when printing long unsigned numbers, one would turn to use `"%lu"`. However, this causes further troubles as the number won't print at all. Instead it prints nothing but `%` when using `dbg_sprintf`and `%▶■u` when using `sprintf` and later a print function to print to the screen.

**Comment by mateoconlechuga** [comment]
This is a fault of TI, since we use the provided sprintf routines within the bootcode in order to save space. This only supports a limited subset of format specifiers. The only real way to fix this is to use a custom-rolled sprintf routine.

**Comment by AlexGustafsson** [comment]
Mitigation for future reference:

The built in `sprintf` routine does not support `%lu`. By implementing a function `ultoa` that takes an `unsigned long` (`uint32_t`) and converts it to a string we can look past that issue. If further formatting is needed, lets say you need to print "a=%lu", there are further issues to tackle. The `sprintf` routine does not support `%s` either, therefore we need to format the string in steps. First format the string as wanted and then use `strcat` to concatenate the formatted string and the result from our `ultoa` function.

Example implementations (not the fastest nor safest, but working).

Converting an `unsigned long` to a string:
```C
void reverse(char *string, int length)
{
    int i = 0, j = length - 1, temp;
    while (i < j)
    {
        temp = string[i];
        string[i++] = string[j];
        string[j--] = temp;
    }
}

int ultoa(uint32_t value, char *string)
{
  int i = 0;
  while (value)
  {
      string[i++] = (value % 10) + '0';
      value = value / 10;
  }

  reverse(string, i);
  string[i] = '\0';
  return i;
}
```

Example usages

```C
char formattedString[BUFFER_SIZE];
char tempString[BUFFER_SIZE];

uint16_t a = 2612;
uint8_t b = 2;
/* ipow calculates the integral power (as we are used to in mathematics, not an estimate) */
uint32_t c = ipow(a, b);

sprintf(formattedString, "%d^%d=", a, b);
ultoa(c, tempString);
strcat(formattedString, tempString);
```
