### ISSUE TITLE
It says wine is needed for 'building", so does that mean there's an app? And can that be downloaded?

### ISSUE THREAD

**Issue by jcgter777** [CE-Programming/toolchain#112]

**Comment by jcgter777** [comment]
WHY? I'm dead

**Comment by mateoconlechuga** [comment]
Because you do not listen.

**Comment by mateoconlechuga** [comment]
How to install wine:

    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install wine

Copy and paste each individual line at the terminal prompt.

**Comment by runer112** [comment]
I understand you have a mac? Install homebrew:

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

And then Wine:

```
brew install wine
```

**Comment by runer112** [comment]
I understand you have a mac? Install homebrew:

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

And then Wine:

```
brew install wine
```

**Comment by jcgter777** [comment]
@mateoconlechuga I tried to install wine, but I needed an ADMIN PASSWORD. I was just wondering if there was a downloadable already built version. 

@runer112 Mateo already showed that to me, but... ADMIN PASSWORD!!!

**Comment by debrouxl** [comment]
Reading this topic makes me think that there might be some confusion going on, between:
* **building the toolchain** itself (what I think "downloadable already built version", two posts above, refers to);
* **building a program using the toolchain**, however said toolchain was built / obtained / installed.

The thing is, *building a program using the toolchain* requires Wine, as it still has to rely on some of Zilog's proprietary programs which only work on Windows and Wine. Even installing an externally built toolchain (in case building the toolchain requires Wine, I haven't checked) would still make you unable to use said toolchain until you have Wine.

As Runer112 wrote, either tell your mom to install Wine, or use the PB

**Comment by adriweb** [comment]
Also, having an old (outdated, even) version of macOS doesn't make it any easier :/
