### ISSUE TITLE
<debug.h> should respect the NDEBUG flag used by <assert.h>

### ISSUE THREAD

**Issue by elfprince13** [CE-Programming/toolchain#12]
`<debug.h>` should provide differing definitions of the functions defined, depending on whether the NDEBUG preprocessor flag is defined. In the case where it is, provide no function prototype, but instead a function-like macro that inserts `((void)0)` on use (cf. the definition of `assert` in `<assert.h>`)

**Comment by MateoConLechuga** [comment]
Fixed in release v1.6
