### ISSUE TITLE
Antivirus thinks ez80cc.exe is a virus

### ISSUE THREAD

**Issue by Elektron72** [CE-Programming/toolchain#121]
I am using Webroot SecureAnywhere. Recently, when I tried to install via the .exe file, Webroot believed ez80cc.exe was a virus, categorizing it as Trojan.Dropper.Gen. Does anyone know why this happened?

**Comment by runer112** [comment]
This happened because anti-virus programs produce false positives sometimes. This is one of those times. ez80cc.exe contains no viruses.

**Comment by mateoconlechuga** [comment]
Feel free to add it to the whitelist for your antivirus, or disable the antivirus when building. This is a common thing when working with computer toolchains.
