### ISSUE TITLE
qsort() is broken

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/toolchain#122]
Input array: {"I", "A", "ZZ", "C"}
Expected output: {"A", "C", "I", "ZZ"}
Actual output: {"A", "ZZ", "C", "I"}

**Comment by mateoconlechuga** [comment]
It's not broken, you just don't know how to use it.

**Comment by mateoconlechuga** [comment]
Proper usage of qsort():

    int compare (const void * a, const void * b ) {
        const char *pa = *(const char**)a;
        const char *pb = *(const char**)b;
        return strcmp(pa,pb);
    }

    int i;
    const char *input[] = {"I", "A", "ZZ", "C"};

    int len = sizeof(input) / sizeof(char*);
    qsort(input, len, sizeof(char*), compare);

    for (i=0; i<len; i++)
        dbg_sprintf(dbgout, "%s\n", input[i]);
