### ISSUE TITLE
dbg_printf should not take a buffer argument.

### ISSUE THREAD

**Issue by elfprince13** [CE-Programming/toolchain#13]
It would be more useful to have `dbg_printf` be an actual function, mimicking `printf` usage. Keep `dbgout` as a global variable, and provide a definition that `sprintf`s to `dbgout`.

**Comment by elfprince13** [comment]
Suggested implementation:

```
int dbg_printf(const char* fmt, ...){
	va_list args;
	va_start(args, fmt);
	vsprintf(dbgout, fmt, args);
	va_end(args);
}
```

**Comment by MateoConLechuga** [comment]
Well, I chose an adaptation of sprintf because vsprintf is not a part
of the standard libraries in the bootcode, and this would add tons of
unnecessary code. There's TI's own debugger printf function that works
exactly like yours, but it only works if the emulator byte is set.

**Comment by MateoConLechuga** [comment]
Actually, I prefer to leave the dbg_printf this way. That way you can write output elsewhere or something rather than to the console. This is one extra argument; it's not that bad :P

**Comment by elfprince13** [comment]
The problem is that I'm trying to maintain API-coherence with the PC version of my code base, and C89 doesn't support variadic macros, so I currently have to have `#define dPrintf(args) printf args`, but there's no way that I know of to unpack the args paren-expression to insert the `dbgout` reference.

**Comment by adriweb** [comment]
@elfprince13: Making a wrapper function with the argument(s) already setup (`dbgout` etc.) should do the trick?

**Comment by MateoConLechuga** [comment]
void dPrintf(const char* fmt, ...){
    va_list args;
    va_start(args, fmt);
    vsprintf(dbgout, fmt, args);
    va_end(args);
}

Works well with v1.6
