### ISSUE TITLE
Calling the solve( function from C

### ISSUE THREAD

**Issue by Decimation** [CE-Programming/toolchain#133]
Is there any way to call the [solve( function](http://tibasicdev.wikidot.com/solve)?

**Comment by mateoconlechuga** [comment]
Why on earth would you want to do that? It's not going to make your program faster, nor is it going to be helpful or easy. Use a standard library to accomplish what you want in C.

Also, please use the language for the task. Basic is suited specifically for working with the OS functions. C is not.
