### ISSUE TITLE
Toolchain setup issue

### ISSUE THREAD

**Issue by hypothermic** [CE-Programming/toolchain#136]
I've set up the toolchain according to the guide in the GitHub pages, however when building the sample project I'm getting an error. Here's the full log of what I tried:
```shell
raven@enforcer:~$ wget -q https://github.com/CE-Programming/toolchain/releases/download/v8.2/linux_CEdev.tar.gz && tar -xzf ./linux_CEdev.tar.gz
raven@enforcer:~$ export CEDEV=~/CEdev && export PATH=~/CEdev/bin && echo $CEDEV $PATH
/home/raven/CEdev /home/raven/CEdev/bin
raven@enforcer:~$ cd ~/CEdev/examples/hello_world/
raven@enforcer:~/CEdev/examples/hello_world$ make
Command 'make' is available in '/usr/bin/make'
The command could not be located because '/usr/bin' is not included in the PATH environment variable.
make: command not found
```

I'm using Ubuntu 17.10. Any help is appreciated!

**Comment by mateoconlechuga** [comment]
You need to include '/usr/bin' in the path variable. What you should have executed when constructing the path:

    export CEDEV=~/CEdev && export PATH=~/CEdev/bin:$PATH && echo $CEDEV $PATH

You should just add this line to your .bashrc so you don't have to do it every time. :)
