### ISSUE TITLE
[macOS] Cannot execute binary file for fasmg

### ISSUE THREAD

**Issue by VeryGoodDog** [CE-Programming/toolchain#137]
When I try to compile the hello_world demo it throws "cannot execute binary file" for "fasmg" and an error code of 126. I don't really know if I set up everything right.

I'm on High Seirra.

**Comment by adriweb** [comment]
Huh...

Let's see... In a terminal window, do this: `ls -al $CEDEV/bin/fasmg` and this: `file $CEDEV/bin/fasmg`. and copy/paste the output here.

**Comment by eado** [comment]
I'm having the same issue. I checked the file type for `fasmg` and it seems that it's compiled for Linux:
`/Users/omarelamri/CEdev/bin/fasmg: ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.2, stripped`

And yes, I made sure that it has permissions to execute:
`-rwxr-xr-x@ 1 omarelamri  staff  51096 May 28 15:07 /Users/omarelamri/CEdev/bin/fasmg`

Thanks!

**Comment by eado** [comment]
It seems to be the same for all other binaries:
`convpng`: `/Users/omarelamri/CEdev/bin/convpng: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=8e9d3eaedfc0e2b18dd3e41b66c1ee96b900ed93, not stripped`

`convhex`: `ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=34d42ddc32ac476ad8412a65bfdef656e5505086, not stripped`

**Comment by VeryGoodDog** [comment]
oh uhh sorry! my computer got super fried after i posted this. i can check the stuff you posted in a little bit

**Comment by VeryGoodDog** [comment]
i just realized that i don't have cedev installed because of my hard drive failure. i will have to set this all back up (yay!) before i can give you any more info.

**Comment by adriweb** [comment]
I guess you both downloaded the linux release from the github releases page, for lack of a mac one (I generally make them, but I guess I didn't, this time).
Anyway, you can build your own latest toolchain for mac and there will be no such issues.

First, delete the CEDev folder in your home directory, then follow the steps here: https://github.com/CE-Programming/toolchain/wiki/Building-the-toolchain#building-on-linux-and-macos

I shall upload a mac build on the release page, too, I guess...

Feel free to reopen the issue if it's still not solved.
