### ISSUE TITLE
Error During Compilation

### ISSUE THREAD

**Issue by killbox998** [CE-Programming/toolchain#138]
Fedora 28
I am having an error when running "make" after "cmake".
``/home/killbox/src/toolchain/src/std/shared/bsearch.c:27:7: error: conflicting types for ‘bsearch’
 void *bsearch(char *key,
       ^~~~~~~
In file included from /home/killbox/src/toolchain/src/std/shared/bsearch.c:10:
/home/killbox/src/toolchain/src/std/stdlib.h:85:7: note: previous declaration of ‘bsearch’ was here
 void *bsearch(void * key,void * base, size_t nmemb, size_t size, int (*compar)(void * ,void * ));
       ^~~~~~~
cc1: warning: unrecognized command line option ‘-Wno-incompatible-library-redeclaration’
make[2]: *** [CMakeFiles/toolchain.dir/build.make:1116: CMakeFiles/toolchain.dir/src/std/shared/bsearch.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/toolchain.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
``

**Comment by jacobly0** [comment]
The cmake build doesn't work at the moment, so please use a clean repo without running cmake.

**Comment by mateoconlechuga** [comment]
Here's the tutorial on building: https://github.com/CE-Programming/toolchain/wiki/Building-the-toolchain
