### ISSUE TITLE
I cannot get sprintf() to work

### ISSUE THREAD

**Issue by onlymx13** [CE-Programming/toolchain#139]
I run code
```c
//all required includes
char * floatToString (double f) {
char buffer[50];
sprintf(buffer,"%f",f);
return buffer;
}
void main() {
//everything necessary to set up gfx
double number = 25.25;
gfx_PrintStringXY(number, 50, 50);
//wait for a keypress and exit
}
```
and the screen gets messed up and the float doesn't print properly. Is this a mistake of mine?

**Comment by jacobly0** [comment]
Using `"%f" ` in a `sprintf` does not work because of TIOS bugs.

**Comment by adriweb** [comment]
Also that buffer variable is on the stack of the function, you shouldn’t return it, it could have complete garbage.

**Comment by onlymx13** [comment]
So then how do I print a float?

**Comment by onlymx13** [comment]
Sorry, I edited to add the function call. So what should I do instead?
