### ISSUE TITLE
<assert.h> depends on <debug.h>, does not include it

### ISSUE THREAD

**Issue by elfprince13** [CE-Programming/toolchain#14]
It's not great form to have weird include-order issues for client files, especially since <assert.h> is defined by the standard. It should probably include debug.h or something along those lines.

**Comment by elfprince13** [comment]
(n.b. this also means that debug.h should also start by #undef-ing it's own macros, since assert.h is required to be able to repeatedly included with different settings w.r.t. NDEBUG.

**Comment by MateoConLechuga** [comment]
Bleh

**Comment by MateoConLechuga** [comment]
Updated release v1.6 to reflect this issue.
