### ISSUE TITLE
ZDS compiler internal error when building

### ISSUE THREAD

**Issue by onlymx13** [CE-Programming/toolchain#140]
```
$ make
C CE SDK Version 8.2
C:\path\src\gfx\cursor.c
C:\path\src\gfx\logo_gfx.c
C:\path\src\main.c
P3: Internal Error(0x83BAF1):
        Please contact Technical Support
make: *** [obj/main.src] Error -1
```
where path is my path to the github repo.
What does this mean/how do I remedy this?
Edit: I am using mingw64 on 64-bit Windows 10. I can build other things. My friends can build this code, but I can't.
Edit 2: Sometimes I get this error instead:
```
$ make
C CE SDK Version 8.2
convpng 6.4 by m.waltz
created icon using 'iconc.png'
flat assembler  version g.i29v6-ez80
C:\CEdev/include/fasmg-ez80/ld.fasmg [661] macro import [555] macro handle [1] macro parse [243] C:\CEdev\lib\cstartup.src [5]:
        .ref _main
macro ? [2] macro REF [5] macro ? [1]:
        . def
Processed: . := global._main
Error: symbol '_main' is undefined or out of scope.
make: *** [bin/PAPRCLPS.bin] Error 2
```
where convpng works but the assembler doesn't.

**Comment by adriweb** [comment]
That means the C compiler from Zilog crashed (yeah it’s a crappy compiler and has many issues). You’ll have to find a way to rewrite your code a bit differently... Copy/Paste it here and we may have some ideas.

**Comment by onlymx13** [comment]
The code is 200-300 lines and on a private repo... I can try to get permission to make it public if that will be needed. The odd thing is that I get the two errors above for the same code. It seems to be random. It also is odd that very small changes to the code allow me to build or not. The third weird thing is that I, on Windows, can build master but not the other branch. My friend @eado, on macOS, can build the other branch but not master. And my friend @jack-the-coder, on Chrome OS (?) can build both. I'm just not sure why this happens.

**Comment by eado** [comment]
Now, both branches are able to compile on macOS. To my knowledge, it's only a windows error.

**Comment by eado** [comment]
@jack-the-coder is on Debian, not Chrome OS.

**Comment by onlymx13** [comment]
But I have no way of tracing the error.

**Comment by PeterTillema** [comment]
You can try to comment out blocks of code, to see where the bug appears.

**Comment by adriweb** [comment]
Yeah it could be something like what @mateoconlechuga said, but if you manage to comment out parts little by little you will probably end up on the offending code... let us know, then we can close the issue if you manage to solve it... or if that's not possible :( (but a workaround is almost guaranteed to exist, even if it has to be ugly...)

**Comment by onlymx13** [comment]
Ok I’ll try that. It’ll be 5-7 hours before I can get home and test it, but I’ll be sure to get back to you guys. Thanks for all your help!

**Comment by onlymx13** [comment]
Thanks! It worked perfectly!

**Comment by mateoconlechuga** [comment]
See Runer :P
