### ISSUE TITLE
Key press detection does not work on pre-Revision I calculators

### ISSUE THREAD

**Issue by onlymx13** [CE-Programming/toolchain#141]
My calc is pre-hardware revision I and cannot run my C program. How do I fix this? I know it is possible because Oiram runs on both kinds of calculators. Sorry for bothering you guys/having so many questions.

**Comment by mateoconlechuga** [comment]
Have you tried any of the example key press programs?

**Comment by onlymx13** [comment]
I will when I get home in about 4-5 hours. Are they intended to work on both types of calculator? Also, is CEmu’s hardware revision emulation setting accurate? I don’t want to mess up my hardware calc.

**Comment by mateoconlechuga** [comment]
Yes, CEmu emulates it correctly. The key examples are located in `keypad_multiple_keys` and `keypad_arrows`. Hope this helps!

**Comment by onlymx13** [comment]
I tried them, but CEmu is not emulating the problem that occurs on my calculator. Maybe it's not a hardware revision error. How do I check my hardware revision?

**Comment by adriweb** [comment]
Why do you ask if you said "My calc is pre-hardware revision I " :P
Anyway, what are the few characters at the back of the calc, to the right of its serial number? It looks like `L-0616E`

**Comment by onlymx13** [comment]
L-0215

**Comment by mateoconlechuga** [comment]
I have no idea what you are talking about. Closing issue until some actual information come about.

**Comment by adriweb** [comment]
Btw you wouldn’t want to make stuff that run on pre-I only anyway.

**Comment by mateoconlechuga** [comment]
Adriweb, this has nothing to do with revisions.

**Comment by onlymx13** [comment]
I want it to run on both. I’m using
```c
if (kb_7 & kb_Enter){}
```
Which doesn’t seem to work on my calc.

**Comment by onlymx13** [comment]
That could be true, but we’re on the same OS with the same libraries. What
could be the difference?

**Comment by adriweb** [comment]
@mateoconlechuga well maybe, but the title sure makes it look like it :p

Anyway, the samples should work on all revs (unless we broke something at some point...) so something else must be wrong.

**Comment by jacobly0** [comment]
That should be `kb_Data[6] & kb_Enter` to detect the `[enter]` key or `kb_Data[3] & kb_7` to detect the `[7]` key.

**Comment by onlymx13** [comment]
Sorry, typo. That’s what I have. It works on CEmu regardless of what
hardware I’m emulating, but on my calculator it doesn’t. I had more
homework than I expected last night, but tonight I’ll test those keyboard
examples on my hardware calc. Sorry.

**Comment by mateoconlechuga** [comment]
I'll bet it's a CEmu bug that needs fixing :)

**Comment by onlymx13** [comment]
I tried keypad_arrows and it worked on my hard calc. Maybe it's because I set the scan mode to continuous instead of calling kb_Scan in the main loop...?

**Comment by onlymx13** [comment]
one reset later... No, that wasn't it. I tried that and it still froze. It seemed like polling the keyboard itself froze.
Here's the main loop. It is a cursor-based game.
```c
while (!(kb_Data[6] & kb_Clear)) {
//other stuff
		if (!key & prevkey) handleButtons();
		prevkey = key;
		if (!kb_Data[7] | i%20) continue; // add lag so the cursor isn't hyperspeed
		gfx_Sprite(behind_sprite, cursorx - 8, cursory - 8);
		if (kb_Data[7] & kb_Right) cursorx += (cursorx != 318);
		if (kb_Data[7] & kb_Left) cursorx -= (cursorx != 0);
		if (kb_Data[7] & kb_Up) cursory -= (cursory != 0);
		if (kb_Data[7] & kb_Down) cursory += (cursory != 238);
		drawCursor();
	}
```

**Comment by mateoconlechuga** [comment]
So where is the part where you call kb_Scan()?

**Comment by onlymx13** [comment]
I call kb_SetMode(MODE_3_CONTINUOUS); beforehand instead.

**Comment by mateoconlechuga** [comment]
And who said that you could do that? :P

**Comment by onlymx13** [comment]
It works on CEmu and my friends' calcs, and is much faster.

**Comment by mateoconlechuga** [comment]
Who said that it does what you think it does? Because it most certainly doesn't.

**Comment by onlymx13** [comment]
What does it really do, then?

**Comment by onlymx13** [comment]
Wait... On my calculator, it DOES sometimes accept keypresses. It just lags a lot...? Oh, that's it, it just lags a lot. I get it! But why would it lag on mine?

**Comment by onlymx13** [comment]
Just transferred all my programs and appvars to CEmu and it doesn't lag there. By lag, I mean <1fps.
