### ISSUE TITLE
SetFontData bug

### ISSUE THREAD

**Issue by Duarh** [CE-Programming/toolchain#144]
Hello,

I think I encountered a bug with SetFontData. Some modified characters are not displayed correctly. An example:

https://pastebin.com/HmR84LjM

This is the font used: https://github.com/CE-Programming/toolchain/files/2116811/font.zip

Here is the result: https://user-images.githubusercontent.com/34426151/41622654-90d56c28-7410-11e8-8806-a5e94ac2b56c.png

The characters !.:>| (33, 46, 58, 62 and 124) are not displayed as they should be. I noticed that .:| are all one pixel large, so I guess there is a problem with one pixel large characters. !> are not though so there should be another issue.

Also it looks really strange after the 160th character.

**Comment by runer112** [comment]
It looks like this is an 8-pixel-wide monospaced font. When setting the font, you should also use `gfx_SetMonospaceFont(8)`.

**Comment by mateoconlechuga** [comment]
Alternatively you can also use `gfx_SetFontSpacing` to set the individual spacing requirements for each character. In most cases though `gfx_SetMonospaceFont` will do the trick.
