### ISSUE TITLE
Memory layout graphic is missing

### ISSUE THREAD

**Issue by Eeems** [CE-Programming/toolchain#148]
The memory layout wiki article has an image embedded that will break down the available memory. This image seems to be missing though. It's trying to link to https://github.com/CE-Programming/documentation/blob/old/images/tutorials/c/ram_c_layout.png?raw=true but the image no longer seems to live there.

**Comment by adriweb** [comment]
An always valid link is: https://raw.githubusercontent.com/CE-Programming/documentation/7c4d2311335b70c99c9e781b90259ec1505d0e2e/images/tutorials/c/ram_c_layout.png
