### ISSUE TITLE
C++ Compatibility

### ISSUE THREAD

**Issue by Paul-Hoerenz** [CE-Programming/toolchain#158]
Please add a c++ compatibility

**Comment by mateoconlechuga** [comment]
Why don't you

**Comment by Eeems** [comment]
To follow up on what @mateoconlechuga said. This is the CE C Software Development Kit. Not the The CE C++ Software Development Kit or The CE <insert language here> Software Development Kit. Implementing C++ support is outside the scope of this project.

**Comment by adriweb** [comment]
I mean, some things do work already. See some commits of mine precisely about that ( fd3a6f52e4a7882f5269458c8e35dff8e0b5f5d0 , 323e26c52f879a5762bde9715f234b202526528e , ec1421acc32f1d707f64ebb9a135fb36adcb2055 ).

I’ve had a few raw C++ samples on the Project Builder too (but obviously, no stdlib - for fun I've added some things like strings and unordered_map from TinySTL) working through [llvm-ez80](https://github.com/jacobly0/llvm-z80). See [here](https://gist.github.com/adriweb/1eb36aa2c7331997723602e14f13288b) for the tinySTL example, and [here](https://tiplanet.org/pb/?id=1381_1495651975_487d1644da) for a simple 2d Point class and usage.
But that compiler is obviously not ready enough to be stable etc.
