### ISSUE TITLE
Linker Script: Symbol 'length' is undefined or out of scope

### ISSUE THREAD

**Issue by gplastic** [CE-Programming/toolchain#166]
Mac OS High Sierra, C CE SDK Version 8.4

I don't know a lot about compilers, linkers, or C, but this error with the linker script is preventing me from using the compiler:

```
C CE SDK Version 8.4
flat assembler  version g.i9wqj-ez80
eval [1] /Users/nota/CEdev/include/.linker_script [2]:
	symbol __len_bss = bss.length
macro symbol [4]:
	global.symbol := value
Processed: global.__len_bss := bss.length
Error: symbol 'length' is undefined or out of scope.
```
Thank you for your time.

**Comment by mateoconlechuga** [comment]
The master branch isn't stable. You can use the release source files to build instead. Hopefully in the future we can migrate to a `development` branch.

**Comment by jacobly0** [comment]
This happened because an old version of the linker was used because `git submodule update` wasn't run before compiling.
