### ISSUE TITLE
Add sscanf/fscanf functions to stdio

### ISSUE THREAD

**Issue by MCJack123** [CE-Programming/toolchain#171]
I wanted to port a program to the TI-84+ CE, but it relies heavily on sscanf, and it doesn't seem like there's a reason not to implement it for strings or files (though scanf isn't necessary since there isn't standardized keyboard input). I would write something myself but I'm not very familiar with C; especially the version of C this uses.

**Comment by mateoconlechuga** [comment]
Sounds hard. Any program that uses sscanf is probably garbage anyway.

**Comment by MCJack123** [comment]
I only used it because it's convenient, but I can work around it for now.

**Comment by adriweb** [comment]
Issue superseded by #204.
