### ISSUE TITLE
Win32/Unwaders.C!ml malware detected in fasmg.exe 

### ISSUE THREAD

**Issue by OulanB** [CE-Programming/toolchain#180]
This morning, windows defender on windows 10 (1809 17763.134)
detected this malware in fasmg.exe 
I reload it from this site and it is still detected

Is this a false positive ?

(I need it to continue my HP41CX emulation on the TI83 PCE ! )

**Comment by debrouxl** [comment]
It's extremely likely that this detection is yet another false positive of one of the incarnations of pro-virus software snake oil.
<Insert rant about inefficient, highly insecure and counter-productive pro-virus software here...>

**Comment by OulanB** [comment]
Finally I got the source of fasmg, patched it manually and reassembled it on my mac as a windows binary.

Something should have changed, as now the patched binary version if4si-ez80 is not detected as malware anymore.
