### ISSUE TITLE
Setup Help needed fast

### ISSUE THREAD

**Issue by TimmyTurner51** [CE-Programming/toolchain#181]
When running  make /NES84 I got this:
make: *** No rule to make target `/NES84'.  Stop.

I was trying to use NES84 for the CE from github and I tried making it from the folder like the examples provided by the toolchain file (like examples/hello_world)

**Comment by adriweb** [comment]
That initial slash is oddly suspicious. Try to clean up the path and/or the names here and there.

**Comment by TimmyTurner51** [comment]
First, I typed this:   export CEDEV=~/CEdev && export PATH=~/CEdev/bin:$PATH
I am using mac and I know these variables exist. I just tried this in terminal:
make /Users/austin\ turner1/Downloads/AOCEmpires $ make
I am trying every possible way. If I type 
make ~/Users/austin\ turner1/Downloads/AOCEmpires $ make
I also tried this:
make ~/Users/austin\ turner1/Downloads/AOCEmpires $ make
Maybe something is wrong. I even tried:
~/Users/austin\ turner1/Downloads/AOCEmpires $ make
and It gives me: -bash: /Users/austin turner1/Users/austin turner1/Downloads/AOCEmpires: No such file or directory , but it is. I renamed the folder so it is AOCEmpires. Can anyone help with this?

**Comment by debrouxl** [comment]
Don't use spaces in your paths: in general, many scripts on Windows, MacOS X, Linux and others do not support them.

**Comment by adriweb** [comment]
The space inside your username may be causing these issues. I'd suggest temporarily trying everything from within `/tmp` for instance, just to make sure it works there and confirm the initial issue was the space.

**Comment by TimmyTurner51** [comment]
I have tried with the space and without the space in my username.

**Comment by mateoconlechuga** [comment]
> I have tried with the space and without the space in my username.

No, you didn't.

Anyway, this has already been answered on Cemetech, but you do not give the name of the directory. You simply type `make`. Nothing else. It's not that hard.
