### ISSUE TITLE
Need convfont

### ISSUE THREAD

**Issue by drdnar** [CE-Programming/toolchain#186]
While it IS possible to create fonts by hand (see `drsans/`), it is definitely much more enlightening to use a GUI editor. There aren't a whole lot of bitmap font editors, but Fony should run under WINE, unlike that MFE junk that needs Mono. I might even write an on-calc editor.

Sadly, I don't know anything about Webapps, but @Adriweb said all the cool projects are Webapps, so I'm sure he can handle that.

**Comment by adriweb** [comment]
I mean, sure, a web app would be cool as we wouldn't have to care about OS compatibility but if there is already a tool that exists and works (you mentioned Fony), then there's no need to work on something new just for the sake of it :p

In any case, if we want some native tool anyway, @mateoconlechuga is the conversion master as he already takes care of such programs, in C (making them emscriptenable if needed) - for instance convhex, convpng...

**Comment by adriweb** [comment]
Also, ince that will require some GUI, I guess it'd be done with C++ and Qt.
Since Qt's latest version (or is it the upcoming one, at least even more) has a WASM build target, that works well for single-threaded apps (that don't use fancy web-incompatible libraries). So if we end up having some native Qt convfont, we could probably at the same time have a web version for free :D

**Comment by adriweb** [comment]
Looks like @drdnar's working on it :)

```
13:15:09 <@DrDnar> sweet, I got FNT import working in MFE, so I understand the format well enough to write convfont.
13:15:53 <@DrDnar> Though only for the 3.0 format version. I guess I should do the 2.0 version, too, since it seems fairly common.
```

**Comment by drdnar** [comment]
convfont is now a thing. If I'm lucky, it even works properly. Still need to do more extensive testing, but that's for another issue.

**Comment by runer112** [comment]
Where is it?

**Comment by adriweb** [comment]
In the devel branch (though the last few commits could be squashed)
