### ISSUE TITLE
[macOS] Build environment setup issues

### ISSUE THREAD

**Issue by AlmaDev** [CE-Programming/toolchain#187]
When trying to make "hello world" example I get an error that says /include/.makefile. No such file or directory.

I am on a mac. The issue is there is no such file named makefile in your include directory.

**Comment by AlmaDev** [comment]
![Screen Shot 2019-03-21 at 9 38 52 PM](https://user-images.githubusercontent.com/44857611/54795259-c7217080-4c21-11e9-9515-455c328a182d.png)

**Comment by Eeems** [comment]
It sounds like you didn't follow the [install guide](https://github.com/CE-Programming/toolchain/wiki/Installing-on-Linux-or-macOS)

**Comment by AlmaDev** [comment]
> It sounds like you didn't follow the [install guide](https://github.com/CE-Programming/toolchain/wiki/Installing-on-Linux-or-macOS)

I tried following the exact steps and I got the same response

**Comment by adriweb** [comment]
Doesn't look like it?
At least, the fact that it tries to load `/include/.makefile` means that the prefix (`~/CEdev/`) is missing, probably because your `$CEDEV` environment variable is empty/unset.
Check with `echo $CEDEV`. It should print `/Users/yournamehere/CEDev`. If it doesn't, it looks like you didn't setup the env var correctly.

**Comment by AlmaDev** [comment]
This is what my path setting code looks like:
![Screen Shot 2019-03-22 at 10 54 16 PM](https://user-images.githubusercontent.com/44857611/54860779-7c712880-4cf5-11e9-9f91-643c3912661d.png)

**Comment by AlmaDev** [comment]
And when I do $CEDEV it prints nothing

**Comment by adriweb** [comment]
* Did you re-open a terminal window after saving that `.bash_profile` file?
* Are you using Bash as shell?
* What happens if you try `export CEDEV=~/CEdev && export PATH=~/CEdev/bin:$PATH` in a new terminal window and do `echo $CEDEV` and `ls $CEDEV`?

**Comment by AlmaDev** [comment]
Thanks, the make command now works but i get this error:
![Screen Shot 2019-03-22 at 10 54 16 PM](https://user-images.githubusercontent.com/44857611/54860844-7f204d80-4cf6-11e9-88f8-df0cbda3356a.png)

**Comment by AlmaDev** [comment]
Do i need to reinstall wine?

**Comment by adriweb** [comment]
Well, that's not on our side anymore considering your wine install seems to be broken (?!), so I'm not sure we can really help here. I have the same setup and everything works fine...

Which mac (hardware and software) do you have?

Try `brew update && brew upgrade && brew reinstall wine`

**Comment by AlmaDev** [comment]
Im using Mac OSX High Sierra but ill try the commands tommorow.

**Comment by adriweb** [comment]
High Sierra should be just fine - but I fail to see why there'd be missing/bad binaries for wine, especially regarding the architecture.
What kind of mac hardware do you have?

**Comment by AlmaDev** [comment]
![Screen Shot 2019-03-22 at 11 10 53 PM](https://user-images.githubusercontent.com/44857611/54860933-c824d180-4cf7-11e9-855b-6e2427e45921.png)

**Comment by adriweb** [comment]
Should be fine... I'll let you know if I have any idea.

For reference, when I do `file /usr/local/lib/libwine.1.0.dylib` I get `/usr/local/lib/libwine.1.0.dylib: Mach-O dynamically linked shared library i386`.
Which is 32-bit, on my 64-bit machine, sure, but still works fine now.

**Comment by AlmaDev** [comment]
Ok, thank you

**Comment by AlmaDev** [comment]
I get the same result

**Comment by adriweb** [comment]
Maybe you ended up finding a bug with wine on old Macs :( Would be rather surprising though.

**Comment by mateoconlechuga** [comment]
marking this as an external issue with `wine`. Feel free to reopen if you need more assistance.
