### ISSUE TITLE
Shifting is broken when the amount is greater than or equal to the corresponding clip region dimension

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/toolchain#190]
**Issue:**
Running
`gfx_SetClipRegion(0, 2, LCD_WIDTH, 4);`
`gfx_ShiftUp(2);`
will shift the entire screen up, instead of just the given region.

**How to reproduce:**
Take the gfx_sprite example, and insert those two lines, and a `while (!os_GetCSC());` right before `gfx_End()`.
`make` the program, run it on a calc, examine the position of the sprites on-screen, press any key, and observe as everything moves up.

Or just download the zip where I did that: https://drive.google.com/open?id=1Y268OqTtyDNdJCiBcTLucw9ZACSaF_rf

**Comment by KryptonicDragon** [comment]
I'll note that I'm using C CE SDK Version 8.5

**Comment by runer112** [comment]
There's definitely a bug that the shift operations behave badly if the shift amount is greater than or equal to the corresponding clip region dimension.

**Comment by mateoconlechuga** [comment]
Let's say this is undefined behavior and close it.
