### ISSUE TITLE
CopyRect

### ISSUE THREAD

**Issue by commandblockguy** [CE-Programming/toolchain#192]
It would be neat if there was a CopyRect function:
`CopyRect(uint24_t copyX, uint8_t copyY, uint24_t newX, uint8_t newY, uint24_t width, uint8_t height, gfx_location_t source);`
Which could copy a rectangle from one location to another.
This would make it easier to copy stuff around as it would eliminate the need for allocating a sprite, then using GetSprite to copy into that, then drawing the sprite again. It would also allow you to copy something the entire width of the screen up or down at once, rather than requiring you to use two screen halves.
You could change source in order to blit to the currently set draw location from the opposite location, which would be useful if you are trying to make a sliding animation and wanted to copy a static part of the last frame into the current one, but at a different location.

**Comment by mateoconlechuga** [comment]
Closed and added with 0cf0a21, 2cf31fc, and 45dfc40.
