### ISSUE TITLE
Using Prompt & Disp

### ISSUE THREAD

**Issue by ProjectBarks** [CE-Programming/toolchain#200]
Hi all,

I thought the project was super cool and got it running on my machine but I was wondering if it was possible to call to native basic commands such as: prompt, Disp and ect from C?

My hope was that this could be used to write faster algorithms that run on Ti 84 but work as if it was written in the basic interface. I am aware of `os_GetStringInput` but it does not work anything like `prompt`.

**Comment by mateoconlechuga** [comment]
Well, the main issue is that C doesn't really play nicely with the OS on the calculator. We've had many recommendations about adding these features, but I wouldn't expect anything instant in the short term. I'll leave this issue open so we can implement them; but for now you may just want to try writing a custom input routine using `os_GetCSC()` and similar.

**Comment by adriweb** [comment]
For some of the functions like the two you mentioned, I suggest you monitor #204 as it will eventually be able to (be made to) work like you'd want to.

**Comment by mateoconlechuga** [comment]
Sorry of you were looking to support this :( On the plus side; printf and other IO things are implemented.
