### ISSUE TITLE
Functions like scanf, fgets, getline, readline...

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/toolchain#204]
As discussed briefly on IRC, originally for a feature request by @killlmoo.
But here it is in a more formal way so we can gather ideas, solutions and stuff.

**Context**:
```
12:05:28 <sdk-user> Well, it would be nice to have: scanf, fgets, getline, readline, and the whole ncurses. Without that, the hack fills a need.
12:05:44 <@MateoC> Well it would be nice wouldn't it
[...]
12:08:22 <@MateoC> I'll go write all those things this week
12:08:29 <@MateoC> But I need a GitHub issue
```
_(mentioned hack being `os_GetStringInput`, and the whole discussion was sparked by what's in #202)_

**Initial brainstorm**:
```
12:21:31 <@MateoC> I think we should have a way to do user input callbacks
12:21:50 <@MateoC> So fgets etc can be use a defined method of input
12:22:20 <@MateoC> And a user can give their own method
12:22:33 <@MateoC> And it would return some bytes and a size
12:23:26 <@MateoC> Then people can avoid having to only use fgets and similar for only OS functions 
12:23:32 <@Adriweb> [...] why do we need a size if we can just nul terminate the string?
12:24:06 <@MateoC> Size is for the input callback :p
```

**Use cases (and tests/examples to create)**:
* usage in a simple homescreen program
* usage in a simple graphx program

**Notes**:
The [CE port of nspire-io](https://github.com/adriweb/nspire-io) covers some of the needs in a specific way, but of course, as is, it's made to run inside the "terminal". Could give some inspiration, though, and may be useful to some in the meantime. As @mateoconlechuga said, "OS input is a whole other story"

**Comment by killlmoo** [comment]
In the ball park of this sub, are there any plans to have a printf? If I were to make a printf, what should be accepted as stdio?

**Comment by mateoconlechuga** [comment]
Can you explain why you think printf is useful? I have not seen any programs that actually need these functions listed above.

**Comment by adriweb** [comment]
Note that if you just want to format a string into an existing string/buffer, `sprintf` already exists. Then you can do whatever with your buffer.

**Comment by killlmoo** [comment]
> Can you explain why you think printf is useful? I have not seen any programs that actually need these functions listed above.
> 
> The whole reason it wasn't implemented is for 2 reasons:
> 
> a) It's a waste of space. Printf would be massive.
> b) The user should be able to supply their own input/output routines. This is not a standard qwerty keyboard, and output can go to pretty much anything. It's not a terminal interface!

Since sprint already exists making printf using it should not take up that much space, although, why waste what little space there is.

**Comment by mateoconlechuga** [comment]
`sprintf` is compiled into the OS. It doesn't take up any extra space.

It also doesn't support all the things printf supports, such as floats, scientific notation, etc. If you want a "printf" that supports basic integers, then sure. Anything else will be a couple kilobytes in size, when a user may just be using it to print a few strings. There is no advantage to having it other than helping people be able to learn C by reading tutorials.

**Comment by mateoconlechuga** [comment]
So um. In related news to this topic; there's a new commit for enabling an embedded `printf`: f6aa43c

The main reason it is implemented now is because the llvm toolchain allows this to be much cleaner and better integrated for the user.

I'll see about adding the other functions soon.

**Comment by mateoconlechuga** [comment]
The `fgets` function has been added as well. I'm not sure if `scanf` and related functions ever make sense to add; because they are horribly insecure and easy to get wrong... but I could be swayed into it if another issue is opened. For now though I feel like this issue can be closed.
