### ISSUE TITLE
FILEIOC Suggestion: Duplicate(

### ISSUE THREAD

**Issue by calclover2514** [CE-Programming/toolchain#205]
This command would be very useful for things like backup programs.
Same syntax as Rename(Var1,Var2), except instead of renaming a variable, it will create a duplicate of Var1 with the name Var2.

**Comment by runer112** [comment]
Considering you could implement a function that does this in just a few lines, and that a native function would be implemented in basically the same way with no significant benefits, I don't see why this needs to exist.

**Comment by mateoconlechuga** [comment]
I agree. I'm not seeing the benefit as a library function.
