### ISSUE TITLE
ti_GetDataPtr() acting weirdly

### ISSUE THREAD

**Issue by acagliano** [CE-Programming/toolchain#206]
I'm reporting this to you because as I debug it, this seems more like a problem with ti_GetDataPtr(). From the debug output I can see that the first time (right after program load/reindexing) the return from ti_GetDataPtr() is 3 bytes more than it should be. Because of the pointer being returned within the function, I'm fairly certain nothing else could affect it, other than me elsewhere mistakenly holding the file open, but I've checked for that. Also since, as you can see, the debug print of the returned pointer is immediately after the function call, i doubt it would have been affected by any of my that follows. The other weird part is that after this weirdness happens once, it does not happen again until I re-index or reload the program. Also, it seems to not occur anywhere else in my program. The code in question is below, and the github repo holding the entire source is below that.

```c
void av_RestoreSnapshot(snapname_t* snap, uint24_t which){
    size_t size;
    ti_var_t file, snapfile;
    ti_CloseAll();        // I added this in later just to make sure I wasn't holding files open. Same bug.
    if(snapfile = ti_Open(snap->snapname, "r")){
        char* snapdata;
        ti_Rewind(snapfile);
        snapdata = (char*)ti_GetDataPtr(snapfile);
        dbg_sprintf(dbgout, "Pointer: %u\n", snapdata);
        dbg_sprintf(dbgout, "Snapname: %s\n", snap->snapname);
        dbg_sprintf(dbgout, "Progname: %s\n", snap->progname);
        dbg_sprintf(dbgout, "Progtype: %u\n", snap->progtype);
        dbg_sprintf(dbgout, "Index: %u\n", which);
        while(which){
            snapshot_t *curr = (snapshot_t*)snapdata;
            snapdata += curr->savesize;
            which--;
        }
        ti_DeleteVar(snap->progname, snap->progtype);
        if(file = ti_OpenVar(snap->progname, "w", snap->progtype)){
            snapshot_t *curr = (snapshot_t*)snapdata;
            dbg_sprintf(dbgout, "Pointer: %u\n", curr);
            dbg_sprintf(dbgout, "Type: %u\n", curr->type);
            dbg_sprintf(dbgout, "Name: %s\n", curr->name);
            dbg_sprintf(dbgout, "Size: %u\n", curr->size);
            ti_Write(curr->data, curr->size, 1, file);
            ti_Close(file);
        }
        ti_Close(snapfile);
    }
}
```
https://github.com/acagliano/blastfis

**Comment by acagliano** [comment]
Enclosed minimum code to reproduce, and one of the files that I get this error on.
[minimal.zip](https://github.com/CE-Programming/toolchain/files/3221362/minimal.zip)

**Comment by mateoconlechuga** [comment]
Can you describe what the issue actually is, and what you think the code should be doing but isn't?

**Comment by acagliano** [comment]
the first ti_Open and the ti_Delete/2nd Open are two different files.
snap->snapname is the indexed name of the snapshot file.
snap->progname is the indexed name of the program the snapshot is associated with.
This function should:
Open the snapshot file,
Seek to the correct snapshot version's data
Delete the target program to revert.
Create a new empty version of that program.
Write data from the snapshot file to the new empty program.

**Comment by mateoconlechuga** [comment]
Did you see my comment above?

**Comment by acagliano** [comment]
> Did you see my comment above?

Not until i refreshed the page. I'll give it a try.
