### ISSUE TITLE
Add a define for the maximum variable size in one of the header files

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/toolchain#207]
&lt;Kryptonic&gt; 65504 is the largest I can make a var on the CE without ti_Resize() returning 0
&lt;Mateo&gt; Probably :P
&lt;Kryptonic&gt; Will anything explode if I hardcode that into KryptonIDE?
&lt;Mateo&gt; https://github.com/CE-Programming/toolchain/blob/master/src/fileioc/fileioc.asm#L197
&lt;Kryptonic&gt; Or is the number randomly determined the by calculator gods
&lt;Mateo&gt; It&apos;s determined by whatever I felt was reasonable
&lt;Kryptonic&gt; Can you make a constant for it in one of the header files?
&lt;Mateo&gt; It used to be 65514 but TI recently changed it to 65512
&lt;Mateo&gt; I guess so
&lt;Mateo&gt; Something something max file size
&lt;Kryptonic&gt; You gonna do it now or should I open an issue, since you&apos;re always complaining about people telling you about things in here instead of in a github issue.
&lt;Mateo&gt; You should open an issue because I&apos;m very forgetfull :P
&lt;Kryptonic&gt; understandable

**Comment by mateoconlechuga** [comment]
Finished with 01a5e422f280ebc980ae21ac68afc6e96cf2f885
