### ISSUE TITLE
tice.h does not include string.h

### ISSUE THREAD

**Issue by Snektron** [CE-Programming/toolchain#21]
I get a compile error under `memset_fast` due to `size_t` not being recognised.

**Comment by debrouxl** [comment]
size_t is normally defined in stddef.h, according to e.g. N1570. And yup, tice.h should include stddef.h.

**Comment by MateoConLechuga** [comment]
Fixed with [`release v2.1`](https://github.com/CE-Programming/toolchain/releases/v2.1)
