### ISSUE TITLE
Exec format error when installing on 32-bit Debian

### ISSUE THREAD

**Issue by onlymx13** [CE-Programming/toolchain#211]
After installing and correctly configuring wine, I get this error when trying to run `make`.
```C CE SDK Version 8.5
Z:\home\mmmmmmmmmmmmm\CEdev\examples\hello_world\src\main.c
flat assembler  version g.ice6x-ez80
5 passes, 1.5 seconds, 366 bytes.
/bin/sh: 2: /home/mmmmmmmmmmmmm/CEdev/bin/convhex: Exec format error
make: *** [/home/mmmmmmmmmmmmm/CEdev/include/.makefile:186: bin/DEMO.8xp] Error 2
```
This is the output of `uname -a`:
```Linux MMMMMMMMMMMMM 4.19.0-5-686-pae #1 SMP Debian 4.19.37-3 (2019-05-15) i686 GNU/Linux```

**Comment by adriweb** [comment]
Make sure you have every toolchain thing built for 32bit I guess?

**Comment by onlymx13** [comment]
Wow I'm dumb. I built the toolchain from source and everything works now.
