### ISSUE TITLE
Error: Library Version after building from source

### ISSUE THREAD

**Issue by onlymx13** [CE-Programming/toolchain#212]
I built the toolchain from source due to being on a dumb 32-bit architecture. I downloaded the latest C libraries, version 8.4, as a .8xg from tinycc/clibs. After building and sending my program and the 8xg, the program throws Error: Library Version with a Library Name of LibLoad. Is there a new version of LibLoad that I am not aware of? Thanks for any help.

**Comment by adriweb** [comment]
You should build from source with the version "corresponding" to the libs in version 8.4, in order to be compatible.

**Comment by onlymx13** [comment]
How do I do that?

**Comment by onlymx13** [comment]
Is there a way to build the libraries as they are?

**Comment by runer112** [comment]
> You should build from source with the version "corresponding" to the libs in version 8.4, in order to be compatible.

ie. tag "v8.4".

**Comment by onlymx13** [comment]
Seems like the latest release of the toolchain is 8.5. Can I use that or do I need to go back a version?

**Comment by adriweb** [comment]
Yeah actually 8.5 should be ok.
Download the source from here https://github.com/CE-Programming/toolchain/releases/tag/v8.5

**Comment by runer112** [comment]
Alternatively, when you built the toolchain from source, you also built all the C libraries, and you can send those versions. After having successfully built the toolchain, you should have _clibraries/clibs.8xg_ in the toolchain folder. However, note that this is a development snapshot of the libraries and you shouldn't be building anything you plan on distributing to other users with it.

**Comment by onlymx13** [comment]
When trying to build the toolchain, I get `cp: cannot stat 'fasmg-ez80/ez80.inc': No such file or directory

**Comment by adriweb** [comment]
> Alternatively, when you built the toolchain from source, you also built all the C libraries, and you can send those versions. After having successfully built the toolchain, you should have _clibraries/clibs.8xg_ in the toolchain folder.

Well, rather also having done `make release-libs`, but yeah.

**Comment by adriweb** [comment]
> When trying to build the toolchain, I get `cp: cannot stat 'fasmg-ez80/ez80.inc': No such file or directory`

Oh right, that doesn't fetch the submodules...
Looks like you can delete all that and do that instead of the download: `git clone --recursive --branch v8.5 https://github.com/CE-Programming/toolchain.git`

**Comment by onlymx13** [comment]
I built from source, but now there's no `include` folder in the toolchain folder.

**Comment by adriweb** [comment]
did you do `make`, then `make install`, then `make release-libs` ?

**Comment by onlymx13** [comment]
Nope because I'm dumb. Thanks for all the help, I solved my problem!
