### ISSUE TITLE
Header files are always included

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/toolchain#214]
When looking at the object files, it seems that despite the `#ifndef X \ #define X` header files get included in every src program they are included. Check https://github.com/Pieman7373/DungeonCE for an example, `structs.h` is included by all object files, even though it has the proper header header.

**Comment by adriweb** [comment]
(See [here](https://github.com/Pieman7373/DungeonCE/issues/5) for the explanations of what was wrong in the code that was erroring)
