### ISSUE TITLE
[Request] Reduce empty lines in terminal output

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/toolchain#220]
Seems like a bit of a stupid request, but maybe less empty lines in the terminal output after compiling? IMO it makes the output look neater, but it also allows me to reduce the size of the console window in Sublime after building, while still being able to see useful info like the output size :3

The empty lines don't serve any purpose, especially since you already have those two lines with a bunch of hyphens for separating some information.

I.E change this:
```
C CE SDK Version 8.6 
D:\Vexon\Coding\84+CE C Projects\KryptonIDE 2.0\src\caret.c
flat assembler  version g.ice6x-ez80
9 passes, 5.2 seconds, 20124 bytes.


--------------------

input file: KRYEDIT.bin

output file: [KRYEDIT] KRYEDIT.8xp

archived: no

size: 20124 bytes

--------------------

success!



[Finished in 6.9s]
```

Into this:
```
C CE SDK Version 8.6 
D:\Vexon\Coding\84+CE C Projects\KryptonIDE 2.0\src\caret.c
flat assembler  version g.ice6x-ez80
9 passes, 5.2 seconds, 20124 bytes.
--------------------
input file: KRYEDIT.bin
output file: [KRYEDIT] KRYEDIT.8xp
archived: no
size: 20124 bytes
--------------------
success! :D
[Finished in 6.9s]
```

**Comment by KryptonicDragon** [comment]
Hrm, I think the issue is actually with Sublime. I noticed the output doesn't have all those blank lines when I build from a normal console...

**Comment by mateoconlechuga** [comment]
sublime is probably processing line feed / carriage return independently. I'll fix that.

**Comment by mateoconlechuga** [comment]
removed extra spaces.
