### ISSUE TITLE
gfx_SetCharData is broken

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/toolchain#221]
I'm no ASM expert, but I did some debugging in CEmu and it looks like DE and HL are backwards by the time we make it to [this LDIR](https://github.com/CE-Programming/toolchain/blob/a852c0891514f197b92ae67e69ad7e4129783bba/src/graphx/graphx.asm#L3590), and I'm guessing [this RET Z](https://github.com/CE-Programming/toolchain/blob/a852c0891514f197b92ae67e69ad7e4129783bba/src/graphx/graphx.asm#L3588) is meant to return if the `uint8_t *data` passed to gfx_SetCharData() is NULL, but I found that it always executes, even if `uint8_t *data` isn't NULL.

Looking at git blame, I don't know how no one noticed this was broken for 2 whole years, but I keep finding broken routines that no one uses :3

**Comment by adriweb** [comment]
> Looking at git blame, I don't know how no one noticed this was broken for 2 whole years, but I keep finding broken routines that no one uses :3

I guess the fact that it's [not used](https://github.com/CE-Programming/toolchain/blob/21c92126577d6d99ad2c1e911190d16834e294c9/tools/funcs_tested/tested-functions-list.md#L138) in the tests/examples doesn't help...
