### ISSUE TITLE
FILEIOC version

### ISSUE THREAD

**Issue by SingingLakitu** [CE-Programming/toolchain#224]
Hey all!
I just installed the latest toolchain (8.7) and libraries.  However, the toolchain requires FILEIOC version 5, but clibs.8xg seems to contain FILEIOC version 4, resulting in "Error: Library Version".
I fixed the issue on my end, but does this need to be updated?
I'm pretty new to GitHub, so let me know if I should approach this differently.

**Comment by mateoconlechuga** [comment]
I think this has been fixed? It could have just been an issue with the download link.
