### ISSUE TITLE
FileIOC functions crash after ChkFindSym

### ISSUE THREAD

**Issue by beckadamtheinventor** [CE-Programming/toolchain#226]
Title says it all.
FileIOC functions crash if used after ChkFindSym.
I can't use FileIOC's OpenVar() for reading from the Ans variable, it just returns a null for the slot value, so I have to use ChkFindSym.
Otherwise I would just use FileIOC functions.
CE OS version 5.3.0, Revision L.

**Comment by mateoconlechuga** [comment]
Doubt.
