### ISSUE TITLE
Cannot properly clone repository and build from source because convcsv is missing

### ISSUE THREAD

**Issue by PAndaContron** [CE-Programming/toolchain#228]
One of the submodules in this repository is convcsv, however it seems like the convcsv repository linked to no longer exists. It should be [here](https://github.com/mateoconlechuga/convcsv) but it's not. I can't find anywhere else to get the source code and the program won't build without it.

**Comment by mateoconlechuga** [comment]
Why do you need to build from source?

**Comment by adriweb** [comment]
Right, here's a zip of the submodule at that time.

[convcsv_7be077b.zip](https://github.com/CE-Programming/toolchain/files/3859697/convcsv_7be077b.zip)
