### ISSUE TITLE
Sign into app

### ISSUE THREAD

**Issue by erentar** [CE-Programming/toolchain#229]
How can one sign programs into apps?

Would it be hard to implement this?
If you guys are not interested in implementing this feature i'd like to hear how i can do it

Also, thanks very much for everything, C is much more versatile than tibasic

**Comment by mateoconlechuga** [comment]
You cannot sign apps without a special key from TI, which they will not give you.

Unfortunately this is impossible for now.

**Comment by Overload02** [comment]
@mateoconlechuga 
* you can get the key if you reverse compile the ti-connect version on chrome. but it is stated that the product should not uncompiled in any way.

**Comment by mateoconlechuga** [comment]
Guess I must have missed it. You should provide details on how to do so either privately or here.

**Comment by Overload02** [comment]
@mateoconlechuga 
When I started, "but it is stated that the product should not uncompiled in any way."  
the condition where stated here http://education.ti.com/EULA/TIC and this can lead to a fine

I don't know if or where the code has been stored. but hopefully, I don't know if they stored it in the program editor if they did your out of luck. but if not you can try and get the .crx file and use https://crxextractor.com/ to see or get the src code. if you have any luck give me credit!!

**Comment by mateoconlechuga** [comment]
You are just so wrong it is sad.

**Comment by commandblockguy** [comment]
The apps are signed by TI prior to being uploaded to their website. Neither
version of TI-Connect CE does any kind of app signing itself, so the key is
not present in the code for either program.

**Comment by Overload02** [comment]
I did not think you guys would take it seriously. it was an April fools
joke 😂

**Comment by adriweb** [comment]
We knew it wasn't in their app :p

**Comment by erentar** [comment]
In that case, @mateoconlechuga how do you sign cesium?

**Comment by adriweb** [comment]
He doesn't. Just force-installs it manually through a program first. That's also why the app can't be transferred or re-validated.

**Comment by erentar** [comment]
Any instructions on including app.inc in c code?

**Comment by adriweb** [comment]
Not really, no. Feel free to look at Cesium's repo/code.
