### ISSUE TITLE
Internal Error(0xFFC2A5) Please contact Technical Support

### ISSUE THREAD

**Issue by DeathDragon7050** [CE-Programming/toolchain#235]
```
C:\[mypath]\SRC\FUNCS.C  (1,9) : ERROR (217) Cannot open include file "stdbool.h"
P1: Internal Error(0xFFC2A5)
        Please contact Technical Support
 File: C:\[mypath]\SRC\FUNCS.C
 Relative Line: 1
```
Been working fine but they got this error. Tried reinstalling to no avail. (even if i uncomment the include command to include stdbool.h, the next include gets flagged aswell)

**Comment by mateoconlechuga** [comment]
Can you share more code so we can reproduce this? Thanks for the report.

**Comment by jacobly0** [comment]
Also, if your `[mypath]` is too long, then zds will not be happy.

**Comment by DeathDragon7050** [comment]
Hey so somehow the problem resolved itself(?). I changed some code and it just stopped occuring. I think it must have been an accidentally name header file as .c instead of .h. Anyways thanks for responding, sorry if this was useless.
