### ISSUE TITLE
Description without icon

### ISSUE THREAD

**Issue by LogicalJoe** [CE-Programming/toolchain#237]
It would be nice to be able to have the description without the icon (and icon without description?) like the Cesium installer.

**Comment by mateoconlechuga** [comment]
You can already have an icon without a description in the latest release.

**Comment by adriweb** [comment]
Funnily enough, I hit this "issue" just yesterday when adding support for descriptions in the PB :P
Indeed, can confirm that icon only works, icon+description works, but not yet description without icon.
Not a huge problem, but a "nice-to-have" feature, I'd say.

**Comment by mateoconlechuga** [comment]
Convimg now supports this.

**Comment by mateoconlechuga** [comment]
The latest release (v8.8) has been updated, which coincidentally includes support for this.

**Comment by adriweb** [comment]
Turns out that it doesn't in the v8.8 toolchain, but that's fine, it will be in 9.0 :P

**Comment by mateoconlechuga** [comment]
Reopening to make sure it is 9.0

**Comment by mateoconlechuga** [comment]
Verified fixed via 36c6c80 and 9cf32db.
