### ISSUE TITLE
Feature request: F-key menu method

### ISSUE THREAD

**Issue by zbot473** [CE-Programming/toolchain#240]
Is it possible to get a built in call to produce popup f-key menus like this, rather than having to draw them?
![image](https://user-images.githubusercontent.com/49821700/73676802-006c9e80-4683-11ea-9108-0a3797311212.png)

**Comment by mateoconlechuga** [comment]
Well, there's not really a standard call to the OS for this. Most applications already just draw them manually anyway, even from TI. Perhaps a library could be written for this, but it probably isn't high-priority.

**Comment by zbot473** [comment]
Oh, I thought there was.

**Comment by mateoconlechuga** [comment]
It is all based on requirements from this guide:

[sdk83puiguideline.pdf](https://github.com/CE-Programming/toolchain/files/7111894/sdk83puiguideline.pdf)
