### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by dnmalenke** [CE-Programming/toolchain#241]
I am following the instructions here
https://github.com/CE-Programming/toolchain/wiki/Building-the-toolchain
and when I try to build from source, I get these errors

```
mingw32-make[1]: Entering directory 'C:/Users/dnmal/Desktop/Calculator_programming/srldrvce/ogtoolchain/toolchain/src/std'
mingw32-make -C C:/Users/dnmal/Desktop/Calculator_programming/srldrvce/ogtoolchain/toolchain/src/std/fileio BIN=C:\Users\dnmal\Desktop\Calculator_programming\srldrvce\ogtoolchain\toolchain\tools\zds
mingw32-make[2]: Entering directory 'C:/Users/dnmal/Desktop/Calculator_programming/srldrvce/ogtoolchain/toolchain/src/std/fileio'
makefile:36: recipe for target 'build/fseek.src' failed
mingw32-make[2]: *** [build/fseek.src] Error -1073741819
mingw32-make[2]: Leaving directory 'C:/Users/dnmal/Desktop/Calculator_programming/srldrvce/ogtoolchain/toolchain/src/std/fileio'
makefile:54: recipe for target 'all' failed
mingw32-make[1]: *** [all] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/dnmal/Desktop/Calculator_programming/srldrvce/ogtoolchain/toolchain/src/std'
makefile:148: recipe for target 'std' failed
mingw32-make: *** [std] Error 2
```

Did I miss a step?

**Comment by adriweb** [comment]
Maybe your path is too long (too much dir nesting)

**Comment by mateoconlechuga** [comment]
Doesn't look like you installed wine properly.

**Comment by dnmalenke** [comment]
I'm running on Windows 10, and I've tried doing a build from a shorter directory path.

**Comment by mateoconlechuga** [comment]
Why are you not using a release on Windows 10? I mean, if you *really* want to build it we can help, but why?

**Comment by dnmalenke** [comment]
I was attempting to build the srldrvce branch but after that build failed with the same error, I was just trying to build the master build because I thought it would have a better chance of building. I figured out a way to add the serial libraries onto a prebuilt installation. I don't need to build it anymore now. Thanks
