### ISSUE TITLE
Case sensitive compilation on linux

### ISSUE THREAD

**Issue by erentar** [CE-Programming/toolchain#242]
When compiling on linux, if makefile has `NAME ?= lowercasename` the name of program when loaded onto the calculator is also lowercase, making running the program impossible
This issue does not happen on windows.

![calc](https://user-images.githubusercontent.com/40326736/74838970-c5c26180-5324-11ea-94f0-3cbc95230054.gif)
(apologies for the shitty video)

some boring info:
CEmu 1.3
CEdev 8.8

```
> uname -a
Linux 5.4.0-amd64 #1 SMP Debian 5.4.13-1 (2020-01-20) x86_64 GNU/Linux
> wine --version
wine-5.0-rc5 (Debian 5.0~rc5-1)
```
please ask for more if you need

**Comment by adriweb** [comment]
I suppose the toolchain makefile could detect a malformed name, and if so, either warn and try to fix it, or emit a fatal error, forcing the user to choose a proper name.

**Comment by erentar** [comment]
On windows, when i compile a program with lowercase letters in the name, the compiled program is just uppercase, corrected without any prompt
I dont know if this is what you intended, but it definitely is a good feature to have on linux as well

**Comment by mateoconlechuga** [comment]
The makefile will now force the name to uppercase by default, and is controllable with a flag.
https://github.com/CE-Programming/toolchain/commit/00d05dc128bbdee2a959299d46802575875d676c

This is on the llvm branch, which may come out sometime...
