### ISSUE TITLE
Breakable programs

### ISSUE THREAD

**Issue by erentar** [CE-Programming/toolchain#243]
Is it possible to implement breaking into asm code (ideally from the c source)?

![image](https://user-images.githubusercontent.com/40326736/74840453-50a45b80-5327-11ea-9648-fc447d46187c.png)

**Comment by adriweb** [comment]
No, that's rather a debugger feature, which is in CEmu already.

**Comment by runer112** [comment]
Source-level assembly debugging is already in CEmu. Source-level C debugging isn't yet: https://github.com/CE-Programming/CEmu/issues/74.

**Comment by erentar** [comment]
(excuse me for my ignorance)
What do you mean by debugging?
If assembly debugging is present and i compile from c to assembly, what am i missing in between?

**Comment by erentar** [comment]
Sorry, i might have failed to convey my question. I want my programs to be breakable by pressing `ON` key

**Comment by runer112** [comment]
Not really possible. This functionality is provided to TI-BASIC by the OS's interrupt handler. I don't believe we can trick the OS into providing this functionality when running an assembly/C program, and we can't really install our own interrupt handler to do so, either. And even if we could, what would happen when you did this? When a TI-BASIC program is running, the calculator is more or less always in a "normal" operating state, so you can easily and safely return to normal operation when interrupted. But this is not true for assembly/C. The LCD may be misconfigured, resources that should be closed may be left open, critical parts of RAM for the OS may be invalid... The list of problems goes on.

**Comment by erentar** [comment]
Thanks very much for the explanation! I have no idea what i am doing and this info is quite valuable considering the amount of documentation
