### ISSUE TITLE
Detect and call other 8xg programs

### ISSUE THREAD

**Issue by 404meemr** [CE-Programming/toolchain#253]
Since you have a limited amount of heap per program (around 60k I think?), I was wondering if I could call other programs and get return values from them.

**Comment by jacobly0** [comment]
This idea has been discussed, but since that program will overwrite your program's heap anyway you will end up will all of your global variables clobbered, so it isn't considered particularly useful.

**Comment by 404meemr** [comment]
Ah I see. Thanks
