### ISSUE TITLE
I/O Ports

### ISSUE THREAD

**Issue by 404meemr** [CE-Programming/toolchain#254]
I tried connecting to IRC but apparently the site refuses to connect, so I'll just ask here.

Is there any documentation for using PIO to control devices like the screen?
I want to interface with the hardware without using TI's OS.

**Comment by jacobly0** [comment]
[here](https://wikiti.brandonw.net/index.php?title=Category:84PCE:Ports:By_Name)

**Comment by 404meemr** [comment]
thanks
