### ISSUE TITLE
[LLVM] Missing libcalls

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/toolchain#255]
From various tests on the PB, here's what I see that's left to take care of before a release:

Seen in "real projects":
* [x] `_ceilf`
* [x] `_fabsf`
* [x] `_floorf`
* [x] `_roundf`
* [ ] `__llcmpzero` (but probably other __ll stuff too)

Seen by manually testing from [Z80ISelLowering.cpp](https://github.com/jacobly0/llvm-project/blob/z80/llvm/lib/Target/Z80/Z80ISelLowering.cpp#L47):
* `__bbitrev`
* `__bpopcnt`
* `__dadd`
* `__dcmp`
* `__ddiv`
* `__dmul`
* `__dneg`
* `__drem`
* `__dsub`
* `__dtof`
* `__dtol`
* `__dtoll`
* `__dtoll`
* `__dtoul`
* `__frem`
* `__ftod`
* `__ibitrev`
* `__ipopcnt`
* `__lbitrev`
* `__lladd`
* `__lland`
* `__llbitrev`
* `__llcmpu`
* `__lldivs`
* `__lldivu`
* `__llmulu`
* `__llneg`
* `__llnot`
* `__llor`
* `__llpopcnt`
* `__llrems`
* `__llremu`
* `__llshl`
* `__llshrs`
* `__llshru`
* `__llsub`
* `__lltod`
* `__llxor`
* `__lpopcnt`
* `__ltod`
* `__sbitrev`
* `__spopcnt`
* `__ulltod`
* `__ultod`

**Comment by adriweb** [comment]
59c1aab033a261d0b60463928b2c0ba29724866d fixed a few: `_ceilf`, `_fabsf`, `_roundf`.

**Comment by mateoconlechuga** [comment]
Closed in favor of #276

**Comment by runer112** [comment]
There are still some in the list that aren't `double`, `long double`, or `long long` though?

**Comment by adriweb** [comment]
Those would be:

* [ ] `__bbitrev`
* [ ] `__bpopcnt`
* [ ] `__frem`
* [ ] `__ftod`
* [ ] `__ibitrev`
* [ ] `__ipopcnt`
* [ ] `__lbitrev`
* [ ] `__lpopcnt`
* [ ] `__ltod`
* [ ] `__sbitrev`
* [ ] `__spopcnt`
* [ ] `__ultod`

Right?

**Comment by adriweb** [comment]
Closing this in favor of #276, although what's the deal with `_frem`?

**Comment by adriweb** [comment]
`_frem` missing fixed by #537
