### ISSUE TITLE
Anomaly float/double into string

### ISSUE THREAD

**Issue by Hamza-STI** [CE-Programming/toolchain#257]
Hello !

(Sorry for my english)
I try os_RealToStr() to convert  8.7917594692281 into string. Despite a lot of attempts, I get a string with 6 meaningful digits at most.
In digits arguments, I write 9 and this function return 8.791759000 
I try in both LLVM (PB of TI-Planet) and ZDS (latest toolchain offline with CE Dev)

Code :
```c
static void float2str(float value, char *str)
{
    real_t tmp_real = os_FloatToReal(value);
    os_RealToStr(str, &tmp_real, 30, 1, 9); // other values tried as well
}
```

**Comment by runer112** [comment]
I assume that this is because a `float` only really has 7-8 decimal digits of precision, so `os_FloatToReal` only converts 7 decimal digits. Any more digits would be mostly meaningless and likely misleading.
