### ISSUE TITLE
Clipped text printing routines

### ISSUE THREAD

**Issue by Runer112** [CE-Programming/toolchain#26]
Get on it people. *_cracks whip_*

**Comment by MateoConLechuga** [comment]
Eh... this actually wouldn't be too bad to write...

**Comment by MateoConLechuga** [comment]
Closed with commit fe586d7. Everything works rather nicely now; just need some good line and triangle routines :)

**Comment by adriweb** [comment]
( for reference :) )
![text clipping](http://i.imgur.com/a9CAk0u.gif)

**Comment by MateoConLechuga** [comment]
( for more reference :) )
![text clipping](https://usercontent.irccloud-cdn.com/file/xP1SQmC2/evencooler.gif)
