### ISSUE TITLE
srldrvce Doesn't build due to convcsv not existing

### ISSUE THREAD

**Issue by acagliano** [CE-Programming/toolchain#261]
The title should be self evident, but to further detail. 

Steps to Reproduce:
Moved ~/CEdev to ~/CEdev-backup
ran `git clone https://github.com/CE-Programming/toolchain.git`
ran `git checkout srldrvce`
ran `git submodule update --init --recursive`
Got the following error message:
```
Cloning into '/Users/acagliano/toolchain/tools/convcsv'...
remote: Repository not found.
fatal: repository 'https://github.com/mateoconlechuga/convcsv.git/' not found
fatal: clone of 'https://github.com/mateoconlechuga/convcsv.git' into submodule path '/Users/acagliano/toolchain/tools/convcsv' failed
Failed to clone 'tools/convcsv'. Retry scheduled
Cloning into '/Users/acagliano/toolchain/tools/convcsv'...
remote: Repository not found.
fatal: repository 'https://github.com/mateoconlechuga/convcsv.git/' not found
fatal: clone of 'https://github.com/mateoconlechuga/convcsv.git' into submodule path '/Users/acagliano/toolchain/tools/convcsv' failed
Failed to clone 'tools/convcsv' a second time, aborting
```
It appears this repository doesn't even exist anymore.

**Comment by adriweb** [comment]
Yeah, the branch never got updated/rebased (would take quite a bit of work, it'll probably be done eventually...), and since then, the tooling evolved.
Convhex and Convcsv got removed and replaced together by a more powerful single utility, [convbin](https://github.com/mateoconlechuga/convbin).

If you want to see a diff between the invocation of each tool, check the highlighted line here: https://github.com/CE-Programming/toolchain/commit/e7af2b081874f8ed186b66ff3910cb7d2db63a29#diff-8587f51a5c08ba21a0ae5f59cdf84e43R20

**Comment by commandblockguy** [comment]
Although I agree that convbin is a much better tool than convcsv, I have to object to the way that deprecated utilities such as convcsv and convpng have been completely removed. There are still some legacy programs that need the old utilities to build, and it also causes issues with older toolchain branches as is the case here. I see no reason why completely nuking the repository should be preferable to archiving it and adding a warning.

As Adriweb said, it would take a decent amount of effort to rebase the

**Comment by adriweb** [comment]
Yes, I don't know why MateoC fully deleted the repo instead of archiving it. It's not a problem for convpng, since it's all inside the convimg repo (old commits etc).

**Comment by acagliano** [comment]
Well, if there's something that can be done, be it updating the toolchain, making a legacy version of convcsv available, or whatever... I need this branch to build in order to get basic network-testing for TI-Trek off the ground, unless usbdrvce builds, since nanotube has been pronounced dead on arrival as far as libload support goes, last ive heard.
