### ISSUE TITLE
debug.h doesn't document that you need to make debug

### ISSUE THREAD

**Issue by Eeems** [CE-Programming/toolchain#263]
The debug.h documentation should have a little more information in it that you are expected to `make debug` for any command in it to work. Right now it's not clear to a developer that there is a difference. You'd have to look closely at the makefile in the debug sample to figure it out. That or ask for help.

**Comment by adriweb** [comment]
Right, it could be added. Feel free to make a PR, it would en up updated in the docs eventually.

Note that it's still mentioned here: https://github.com/CE-Programming/toolchain/wiki/Debugging

**Comment by Eeems** [comment]
> Right, it could be added. Feel free to make a PR, it would en up updated in the docs eventually.

I don't really like writing documentation, so I'll leave that for someone else :P
> Note that it's still mentioned here: https://github.com/CE-Programming/toolchain/wiki/Debugging

I somehow completely missed that. Thanks for pointing it out.

**Comment by Eeems** [comment]
Whoops, misclicked

**Comment by mateoconlechuga** [comment]
Added in the llvm branch, which will shortly be visible.
