### ISSUE TITLE
jq and jp instructions in external asm hang the assembler

### ISSUE THREAD

**Issue by beckadamtheinventor** [CE-Programming/toolchain#265]
Wasn't sure where to put this issue, so I decided to put it here.
 
In external asm files, sometimes jq and jp instructions will cause fasmg to hang.
The eventual error: ``Cannot generate code in allowed number of passes``
Presumeably an issue with the new ``.alm`` include files.

EDIT: this is an issue with the llvm toolchain

**Comment by jacobly0** [comment]
Closing because can't repro.  However this is a known bug, so if a repro is found please open an issue in the [fasmg-ez80](https://github.com/jacobly0/fasmg-ez80/issues) repo.
