### ISSUE TITLE
Confusion with gfx_Get/SetTileMapped and gfx_TilePtrMapped

### ISSUE THREAD

**Issue by matthewkeller36** [CE-Programming/toolchain#271]
The way the docs and files are currently written are somewhat misleading as the parameter descriptions can be confused with one another. For example, the row parameter is described as "Offset in bytes in the row". This can be misread as the row the tile is located rather than the offset (column). I believe an easy fix to this would be to reverse the parameter input names and reword the two parameter descriptions as:
`#define gfx_GetTileMapped(tilemap, col, row)`
`@param tilemap Pointer to initialized tilemap structure`
`@param col Column of tile in tilemap`
`@param row Row of tile in tilemap`
or something similar.

**Comment by mateoconlechuga** [comment]
Added in the llvm branch, which will shortly be visible.
