### ISSUE TITLE
gfx_SetTextFGColor() doesn't work with full white

### ISSUE THREAD

**Issue by kc-kc** [CE-Programming/toolchain#273]
I was attempting to make white text on a black background using `graphx`, but there seems to be an issue with the rendering when the text color is set to `255`. As an example, the following code renders as such:
```c
#include <tice.h>
#include <graphx.h>

int main() {
    gfx_Begin();
    gfx_SetDrawBuffer();

    gfx_SetTextFGColor(254);  /* Set text color to almost 255, but not quite */
    gfx_SetColor(255);  /* Set line color to 255 */

    while (!os_GetCSC()) {
        gfx_ZeroScreen();

        gfx_PrintStringXY("HELLO", 20, 20);
        gfx_Line(0, 50, 100, 50);

        gfx_SwapDraw();
    }
    gfx_End();
    
    return 0;
}
```
![Image of visible text](https://imgur.com/O0Av6jI.png)
---
However, the text is not completely white, and has a slight pink hue. But when I change the code to use full white, the text doesn't show up on screen:
```c
gfx_SetTextFGColor(255);  /* Set text color to 255 */
```
![Image of invisible text](https://imgur.com/q5amJya.png)
---
I've tried to scan the documentation to see if this is an intended feature or not, but I haven't been able to figure it out. The fact that lines work with solid white, but text doesn't does seem odd. I have tested this on both CEmu as well as hardware, and it doesn't make a difference. Any help would be appreciated.

**Comment by jacobly0** [comment]
Since the default `gfx_TextTransparentColor` is 255, that will draw transparent text unless you change the transparent text color to something else.

**Comment by kc-kc** [comment]
I see, thanks for clearing up my confusion.
