### ISSUE TITLE
Add Actual Time Compiled 

### ISSUE THREAD

**Issue by Overload02** [CE-Programming/toolchain#278]
I think that when the project has finished compiling it should include the time. I get confessed on whether I compiled a project in cmd (when I use the same cmd to compile over and over). Here an example

```
C CE SDK Version 8.6 
D:\Vexon\Coding\84+CE C Projects\KryptonIDE 2.0\src\caret.c
flat assembler  version g.ice6x-ez80
9 passes, 5.2 seconds, 20124 bytes.
--------------------
input file: KRYEDIT.bin
output file: [KRYEDIT] KRYEDIT.8xp
archived: no
size: 20124 bytes
--------------------
success! :D
[Finished in 6.9s]
**[Finished at 12:00p]**
```

Thanks 👍

**Comment by adriweb** [comment]
This should rather be something offered by your shell, though. (Google PS1 time example, or something like that). I'm sure (hope?) there's an equivalent in powershell for windows since you seem to use that.
