### ISSUE TITLE
Abort() is broken in LLVM branch (8de5909) (doesn't compile)

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/toolchain#281]
**The issue:**
Program compilation fails if `abort()` is used in LLVM branch (8de5909).
`make` output:

> [compiling] src/main.c
[linking] bin/DEMO.bin
/home/kryreon/CEdev/meta/ld.alm [1111] macro ? [856] read [7] /home/kryreon/CEdev/meta/../lib/shared/abort.src [13]:
	extern __exit
extern [12] (CALM)
Error: symbol ':globals.__exit' is undefined or out of scope.
make: *** [/home/kryreon/CEdev/meta/makefile.mk:214: bin/DEMO.bin] Error 2

**How to reproduce:**
Take the "hello_world" demo, put `abort()` somewhere in it (preferable in the main() function), and run make.

**Comment by mateoconlechuga** [comment]
Fixed with 8ede84f6
