### ISSUE TITLE
qsort() prototype in stdlib.h is incorrect

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/toolchain#282]
The definition for qsort in stdlib.h is `void qsort(void * base,size_t nmemb,size_t size, int (*compar)(void * ,void * ));`,
but it should be `void qsort(void * base,size_t nmemb,size_t size, int (*compar)(const void * , const void * ));`

**Comment by mateoconlechuga** [comment]
Fixed in e99e35
