### ISSUE TITLE
Not an issue, just need help

### ISSUE THREAD

**Issue by DeathDragon7050** [CE-Programming/toolchain#283]
Where can I ask for help programming in C for the ti84ce? I am having loads of issues and am not very good at C (heavy Python background). I'm getting loads of syntax errors (and other types of errors) and I can't diagnose them because the compiler's errors simply say `Syntax error`. I'm sorry for making a whole new issue on this page but where can I get some help on this?

**Comment by Eeems** [comment]
Have you asked in IRC/Discord yet?

**Comment by DeathDragon7050** [comment]
> Have you asked in IRC/Discord yet?

There's a discord server? Please link it. :)

**Comment by Eeems** [comment]
https://discord.gg/ygvUycq

**Comment by DeathDragon7050** [comment]
Thank you.
