### ISSUE TITLE
Windows: CEDEV environment variable unchangeable 

### ISSUE THREAD

**Issue by JeffreyHuang06** [CE-Programming/toolchain#288]
I had some trouble installing so I first installed the SDK in my Documents folder and then installed in my C:\ drive. I now work exclusively in the C:\ Drive but when I try to change the CEDEV environment variable in the windows registry it doesn't change. What do I do now? Do I put an export command in my bash profile or switch to the original folder or something else?

**Comment by JeffreyHuang06** [comment]
Nevermind I just needed to use mingw32-make install again but now the path works again. How can I use the PREFIX argument to change the install path?

**Comment by adriweb** [comment]
The Windows installer does everything on its own, so it should be fine.

For manually setting env vars, take any tutorial for instance https://www.computerhope.com/issues/ch000549.htm#windows10

**Comment by adriweb** [comment]
> How can I use the PREFIX argument to change the install path?

`make install PREFIX=thePathHere`
