### ISSUE TITLE
ez80-clang: libtinfo.so version

### ISSUE THREAD

**Issue by caseyavila** [CE-Programming/toolchain#293]
Wow, what a great release. thank you guys so much! Right now the provided clang is built against ncurses version 5 (as seen by `libtinfo.so.5`). I'm currently on Gentoo where solely version six is provided (ABI incompatible). This is probably the same with other Linux distributions as well. I can get away with a hack by creating a symlink; the examples compile, but it's far from ideal. Perhaps an updated version of the compiler could be provided?

Maybe I should have reported this on jacobly0/llvm-project. It looks like there's a release already in the making, but I figured people are going to be using the compiler packaged in these releases.

```
$ ldd ez80-clang
./ez80-clang: /lib64/libtinfo.so.5: no version information available (required by ./ez80-clang)
        linux-vdso.so.1 (0x00007ffd4c57f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe4e7ee7000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fe4e7edd000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fe4e7ed8000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe4e7d95000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fe4e7d7b000)
        libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007fe4e7d3e000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/libgcc_s.so.1 (0x00007fe4e7d23000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe4e7b66000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe4e7f16000)
```

**Comment by adriweb** [comment]
Hmm the versioning might be confusing.

For example All Ubuntus I see are on version 6.something for libtinfo5 yet the so is named .so.5, see https://packages.ubuntu.com/hirsute/libtinfo5 (6.2) and earlier distro versions (6.0 for xenial). Seems libtinfo6 has only been there since 20.04. 

Debian has had libtinfo5 for a while libtinfo6 since buster.

Aren't you able to get/build libtinfo5 on your side?

**Comment by jacobly0** [comment]
The `ncurses-compat` package provides `libtinfo.so.5`.

**Comment by caseyavila** [comment]
Makes sense, thanks so much guys.
