### ISSUE TITLE
Documentation lacks any mention of possible issues with the included 32-bit fasmg executable in the Linux release

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/toolchain#297]
Some (Linux) operating systems will refuse to run the included fasmg executable because it is 32 bit. 
This may be un-intuitive to newcomers, since following the instructions in the documentation [https://ce-programming.github.io/toolchain/static/getting-started.html](url) will lead somewhat annoying errors such as
``
make: fasmg: Command not found
`` when trying to build a project, and, even more confusingly,
``
Failed to execute process './fasmg'. Reason:
The file './fasmg' does not exist or could not be executed.
`` when trying to execute fasming directly

I suggest the "Getting Started" guide mentions this issue on Linux and either suggests or provides instructions for how to work around and/or fix this.

**Comment by jacobly0** [comment]
You can fix this by installing `libc6-i386` on debian/ubuntu or similar.  Keeping this issue open until the docs are updated.

**Comment by KryptonicDragon** [comment]
> 
> 
> You can fix this by installing `libc6-i386` on debian/ubuntu or similar. 

Can confirm this works on Ubuntu 20.04.

**Comment by arjvik** [comment]
Alternatively, downloading the `fasmg` executable from the fasm website and replacing the file in the `bin/` folder with a symlink to `fasmg.x64` worked.

**Comment by mateoconlechuga** [comment]
We should probably just include the x64 executable instead.

**Comment by mateoconlechuga** [comment]
Uses 64 bit fasmg now, which is bigger and slower, but whatever -- now people shouldn't need to install other things I guess :(

**Comment by adriweb** [comment]
8% slower according to jacobly, it's not that bad :p
