### ISSUE TITLE
Something is overwriting BSS.

### ISSUE THREAD

**Issue by jacobly0** [CE-Programming/toolchain#298]
This program misbehaves:

```
#include <stdio.h>
#include <string.h>
#include <tice.h>

int main() {
    static char bss_protector[0x1000];
    strcpy(&bss_protector[0x000], "first,");
    strcpy(&bss_protector[0x800], " second");
    os_SetCursorPos(0, 0);
    for (int i = 0; i < 11; ++i) {
        os_PutStrFull(&bss_protector[0x000]);
        os_PutStrFull(&bss_protector[0x800]);
        os_NewLine();
    }
    os_GetKey();
}
```

![screenshot](https://user-images.githubusercontent.com/15544577/107112332-d2d1ac80-6824-11eb-9513-a5840807b57e.png)

[Full project](https://github.com/CE-Programming/toolchain/files/5936448/bss.zip)

Note: Was also reproduced while only calling `os_NewLine()`.

**Comment by jacobly0** [comment]
The only solution I can find is `BSSHEAP_LOW ?= D052C6`.

**Comment by jacobly0** [comment]
Nobody has suggested a better solution, so implementing the only suggestion.

**Comment by adriweb** [comment]
**TODO** at some point: update https://github.com/CE-Programming/toolchain/blob/master/docs/static/images/mem_layout.png from `0xD031F6` to `0xD052C6` (a 8400-byte reduction) -> Total BSS is now 60690 bytes.
