### ISSUE TITLE
Incompatible with Debian 10 Buster

### ISSUE THREAD

**Issue by gek169** [CE-Programming/toolchain#299]
Binaries distributed are incompatible with Debian.

I'm interested in writing code for the TI84 CE but, i cannot run the compiler or convimg or any of that because it requires a more recent glibc

**Comment by adriweb** [comment]
You should (be able to) build the toolchain yourself then: https://ce-programming.github.io/toolchain/static/contributing.html#linux-and-macos

**Comment by gek169** [comment]
I tried to build the Clang, but it gave me a binary which when I ran --version, said it was targetting x86_64.

**Comment by gek169** [comment]
I can't get ez80-clang either. It requires a newer Glibc than debian stable's glibc.

**Comment by adriweb** [comment]
If it's targeting x86_64 and not eZ80, it looks like you didn't follow the instructions here: https://github.com/jacobly0/llvm-project/wiki#build-from-scratch (or you aren't launching the built binary but another clang in your path, maybe)

**Comment by gek169** [comment]
After talking to them, I think that maybe I did actually get a compiler that compiles z80 code, but for some reason it *also* compiled support for my native architecture, so it defaults to that?

**Comment by jacobly0** [comment]
Correct, unless you explicitly disable targets, it will compile all non-experimental targets, and if you use a binary named `clang` it will default to the native target that it was compiled for. You can read about various build options [here](https://llvm.org/docs/CMake.html) but we are neither developers nor maintainers of the llvm build system, so you would get better help from them.

**Comment by gek169** [comment]
it depends on the binary's name?
Who decided that?

**Comment by jacobly0** [comment]
`./ez80-clang --version` is just short for `./clang -target ez80 --version`.  Renaming or symlinking the binary isn't necessary to access all of its functionality, but it allows you to not have to pass `-target ez80` every single time, and if you want it to work with this toolchain, you are expected to rename it to what the toolchain expects it to be named, namely `CEdev/bin/ez80-clang`.
