### ISSUE TITLE
CEDEV environment path variable is not set

### ISSUE THREAD

**Issue by Collin8000** [CE-Programming/toolchain#301]
When i am trying to use make i get  CEDEV environment path variable is not set, im using ubuntu 20.04 btw here is the log

 sudo make
makefile:17: *** CEDEV environment path variable is not set.  Stop.

This is my CEDEV buld variable with path

export CEDEV=/home/path/to/CEdev
export PATH="$CEDEV/bin:$PATH"

**Comment by PrivacyDragon** [comment]
You have to do: `export CEDEV=-path/to/CEdev`
`export PATH=${CEDEV}/bin:${PATH}`

-- 
Securely sent with tutanota.com <https://tutanota.com>.



4 mrt. 2021 18:51 van notifications@github.com:

**Comment by Collin8000** [comment]
in my .bashrc or .profile?

**Comment by Collin8000** [comment]
I still get the error even after i do what you said

**Comment by adriweb** [comment]
Open a new terminal window so that it will load the updates profile with the exported variable.

**Comment by Collin8000** [comment]
It still says makefile:17: *** CEDEV environment path variable is not set.  Stop.

**Comment by Collin8000** [comment]
Would rebooting help

**Comment by Collin8000** [comment]
ok im getting this log if i dont use sudo 

make
[compiling] src/gfx/tileset.c
/bin/sh: 1: ez80-clang: Permission denied
make: *** [/home/collin/CEdev/meta/makefile.mk:236: obj/gfx/tileset.c.src] Error 126

**Comment by PrivacyDragon** [comment]
Are the files set as executable? Is ez80-clang executable? 
-- 
Securely sent with tutanota.com <https://tutanota.com>.



4 mrt. 2021 19:41 van notifications@github.com:

**Comment by PrivacyDragon** [comment]
You can try to see if it works to do: ```chmod +x ${CEDEV}/bin/ez80-clang```

**Comment by Collin8000** [comment]
Thank you so much i tried that and figured out i needed to make all the bin files executable and that was why it was saying permission denied 

This is closed
