### ISSUE TITLE
Linking Issue: " ':globals.__llshru' is undefined or out of scope."

### ISSUE THREAD

**Issue by adakyl** [CE-Programming/toolchain#302]
When I tried to add this math parser to my project [https://codeplea.com/tinyexpr] , it compiled without error but then this:

![Screenshot_2](https://user-images.githubusercontent.com/80306803/110424328-dd6ba580-805f-11eb-8f7a-f92ab63fdbc3.png)
 
What is causing this to happen?

**Comment by jacobly0** [comment]
As mentioned in the v9.0 release notes:
- If your program was using 64-bit types (for instance long long), it may not build (link, more specifically) anymore. In fact, the ZDS compiler even made those 32-bit. If there's enough justified demand for actually supporting 64-bit types properly, we may work on it.
