### ISSUE TITLE
ez80-clang is not marked executable in Linux releases

### ISSUE THREAD

**Issue by commandblockguy** [CE-Programming/toolchain#303]

**Comment by jacobly0** [comment]
See https://github.com/actions/upload-artifact#limitations.

**Comment by Clocks-in-a-Cooler** [comment]
Maybe note that in the documentation? To execute something like `chmod a+x ${CEDEV}/bin/*`?

**Comment by mateoconlechuga** [comment]
Artifacts and releases will now be uploaded in tar format
