### ISSUE TITLE
tice.h documentation is incomplete

### ISSUE THREAD

**Issue by arjvik** [CE-Programming/toolchain#304]
On the [documentation website](https://ce-programming.github.io/toolchain/headers/tice.html) for `tice.h`, there is no mention of functions like `os_RealAdd`, `os_RealMul`, and likely many more. It would be nice to have these functions properly documented.

**Comment by adriweb** [comment]
It's actually specifically excluded from the docs, I'm not sure why. I guess it needs to be documented and the exclusion removed.

**Comment by mateoconlechuga** [comment]
This functions are absolutely useless.

**Comment by arjvik** [comment]
@mateoconlechuga What makes you say they are useless? I made extensive use of them when I created an RPN mode for the Ti84. I only discovered them by reading the source code of `tice.h`.

I'm happy to submit a PR that removes the documentation exclusion comments if it would be well accepted.

**Comment by mateoconlechuga** [comment]
Why on earth would you use those functions for a calculator.

**Comment by arjvik** [comment]
The program I wrote was meant to be an alternative interface to the existing mathematical abilities of the calculator, using Reverse Polish Notation instead of standard infix notation. I did not want to use float arithmetic because they might provide slightly different results in certain cases.

**Comment by mateoconlechuga** [comment]
Fair enough. I guess they can be documented in that case.

**Comment by arjvik** [comment]
I'm happy to submit a PR that adds documentation comments to those functions, would you like me to do so? Or would you prefer that the maintainers handle it yourselves?

**Comment by adriweb** [comment]
A PR is fine :)
And you can even add more docs if you feel it's necessary. 

Also, have you seen the "tireal" C++ header that wraps all the Real functions in a fancy way? It's here: https://github.com/CE-Programming/toolchain/blob/master/src/ce/tireal.hpp

There are some demos in the examples folder, for instance https://github.com/CE-Programming/toolchain/tree/master/examples/standalone/cpp_tireal_test

Could be used for a project like the one you described :p

**Comment by arjvik** [comment]
I had seen that header, however I was writing my program in C and did not want to switch to C++ (I am not super comfortable with it, plus I was on a time crunch and didn't want to waste time wrangling with the toolchain if I had issues switching). I actually found out that the `os_RealXXX` functions existed in `tice.h` by looking at that file.

I will submit a PR today or tomorrow.

**Comment by mateoconlechuga** [comment]
Nice work on the PR
