### ISSUE TITLE
.lib files are included even if lib is not used

### ISSUE THREAD

**Issue by beckadamtheinventor** [CE-Programming/toolchain#309]
[This](https://github.com/CE-Programming/toolchain/blob/b3af65d80950bd16a7d0f09d56c5b8b8588a696f/src/makefile.mk#L202) really shouldn't include libload .lib files unconditionally.
This is bad practice considering you can't redefine any routine defined by any .lib files. Even if you never include the header.
If this could be fixed it would be greatly appreciated.

**Comment by jacobly0** [comment]
It's a [makefile variable](https://github.com/CE-Programming/toolchain/blob/b3af65d80950bd16a7d0f09d56c5b8b8588a696f/src/makefile.mk#L130).

**Comment by Eeems** [comment]
@jacobly0 Looks like that isn't documented: https://ce-programming.github.io/toolchain/static/makefile-options.html
