### ISSUE TITLE
Pointers reset

### ISSUE THREAD

**Issue by DuCouscous** [CE-Programming/toolchain#311]
When I use pointers in my program, my calc reset

my code : 

typedef struct Block {
    int x, y;
} Block;

Block* test;

int main(void)
{
//without that no crash
block->x = 0;
block->y = 0;

return 0;
}

**Comment by adriweb** [comment]
You never allocate `test`, so it is normal that it's not working.

Either use `Block test` so that it's not a pointer (then use `test.x` not `test->x`), or allocate the `test` BLock pointer with malloc, then use it with `test->x` etc.
