### ISSUE TITLE
Pointer issues

### ISSUE THREAD

**Issue by DuCouscous** [CE-Programming/toolchain#312]
I probably made another stupid mistake but here is my code :

Works but when I change Block to Block* and . to -> that reset when launch :(
```c
#include <graphx.h>
#include <tice.h>
#include <keypadc.h>
#include <stdint.h>

void begin(void);
void end(void);
bool step(void);
void draw(void);

typedef struct Block {
    int16_t x,y;
} Block;

Block blocks[255];
int16_t blockCount = 0;

void addBlock(int16_t _x, int16_t _y) {
    blocks[blockCount].x = _x;
    blocks[blockCount].y = _y;
    blockCount++;
}
int main(void) {
    bool partial_redraw = false;

    begin();

    gfx_Begin();

    gfx_SetDrawBuffer();

    while (step()) {
        if (partial_redraw) {
            gfx_BlitScreen();
        }

        draw();

        gfx_SwapDraw();
    }

    gfx_End();
    end();

    return 0;
}
void begin(void) {
    addBlock(20,20);
}

void end(void) {

}

bool step(void) {
    if (kb_IsDown(kb_Key2nd))
        return false;

    return true;
}

void draw(void) {
    for (int16_t i = 0; i < blockCount;i++) {
        gfx_FillRectangle(blocks[i].x-10, blocks[i].y-10, 20, 20);
    }
}
```

**Comment by commandblockguy** [comment]
I would suggest not doing that then.

**Comment by runer112** [comment]
This is essentially the same issue as #311, but with the addition of an array.

**Comment by DuCouscous** [comment]
No because 

> This is essentially the same issue as #311, but with the addition of an array.

No really because i made mistake and changed the name of var lol it was stupid

**Comment by DuCouscous** [comment]
And just for know is a way exist to use pointer in calc ? And is there open src examples ?

**Comment by commandblockguy** [comment]
Pointers behave exactly the same as on the computer, so you can use any C guide.
Why do you need pointers in this instance? What you have currently seems to work fine without them.

**Comment by DuCouscous** [comment]
Ok ^^ thanks
