### ISSUE TITLE
Function to run another program

### ISSUE THREAD

**Issue by commandblockguy** [CE-Programming/toolchain#317]
Might get y'all to stop complaining about everyone else's attempts at writing one :p

More seriously, there's obviously a demand for such a function given that there are multiple people writing their own implementations.

As for the interface, should there be two separate functions, one that exits after running the program and one that re-runs the current program? Also, should there be some mechanism to signal to the program that it's being re-run, or should the user be required to implement that themselves?

**Comment by epsilonfive** [comment]
I think that this is a great idea, I know that the code that I pieced together for VYSION wasn't very good, and definitely had a few bugs. Ideally, I'd like to see it do these things:
-choose whether to run an asm or basic program, probably specified in the arguments
-choose the program to run after the initial program runs (alternatively, this could just be assumed to be the current contents of OP1, and the user could specify whether the reloader should be run)
So the final function might look something like: 
`//Name would be a string, with the first byte being the TI type of the program, then followed by a 2-9 bytes representing the program name (including the null byte)
ti_RunProgram(char *name, bool is_asm, bool use_reloader);`

**Comment by epsilonfive** [comment]
I think that this is a great idea, I know that the code that I pieced together for VYSION wasn't very good, and definitely had a few bugs. Ideally, I'd like to see it do these things:
-choose whether to run an asm or basic program, probably specified in the arguments
-choose the program to run after the initial program runs (alternatively, this could just be assumed to be the current contents of OP1, and the user could specify whether the reloader should be run)
So the final function might look something like:
`//Name would be a string, with the first byte being the TI type of the program,`
`//then followed by a 2-9 bytes representing the program name (including the null byte)`
`ti_RunProgram(char *name, bool is_asm, bool use_reloader);`

**Comment by commandblockguy** [comment]
In my opinion whether it's a TI-BASIC or native program should be determined based on whether the program starts with the assembly program token. You have to skip it anyways when copying the program into memory. Also, that way the user can't write code that tries to run an assembly program as a basic one or vice versa.

The IRC channel seemed to agree on the following interface:
```
void execvv(const char *pathname, char *const argv[], const char *pathname, char *const argv[]);
```
which first calls the first program with the first set of arguments, then the second program with the second set of arguments. You can leave the second pathname NULL to only call a single function, and leave either of the argv's NULL to not overwrite Ans before the program is run.

**Comment by mateoconlechuga** [comment]
How should the return value be delivered to the calling program?

**Comment by epsilonfive** [comment]
The return value should just be passed to the calling program in Ans, I think. Also, it may be good to have a variation of this function that's able to run code at an arbitrary address using a similar interface, and passed size (would be useful for things like running asm from appvars). Perhaps another function, like this:
`void execvv(void *path, size_t size, const char *pathname, char *const argv[]);`

**Comment by epsilonfive** [comment]
Well, it's been over two months...any plans to add the function (no is a fine answer)?

**Comment by mateoconlechuga** [comment]
You clearly have no been paying attention to any of the branches or discussions in #ez80-dev. Not my problem.

**Comment by epsilonfive** [comment]
Yep, it's pretty impressive ignorance on my part. Discord link to the server, for posterity (so that hopefully other people don't run into a similar situation): [https://discord.gg/jAJFWRW6](url).
