### ISSUE TITLE
`make: *** [/home/user/.clibs/meta/makefile.mk:236: obj/main.c.src] Error 126`

### ISSUE THREAD

**Issue by tarneaux** [CE-Programming/toolchain#319]
I am trying to compile the basic example, but I get:
`[compiling] src/main.c`
`/bin/sh: line 1: /home/user/.clibs/bin/ez80-clang: Permission denied`
`make: *** [/home/user/.clibs/meta/makefile.mk:236: obj/main.c.src] Error 126`

OS: manjaro XFCE (Linux)

/home/user/.clibs is where I exteracted the toolchain C libs.
Any ideas?

**Comment by adriweb** [comment]
Have you tried `chmod +x /home/user/.clibs/bin/*` ?

**Comment by tarneaux** [comment]
Ok....
That was pretty simple.
I had chmodded the .clibs directory but apparently it didn't work...
Thanks!
