### ISSUE TITLE
Console Time

### ISSUE THREAD

**Issue by DuCouscous** [CE-Programming/toolchain#321]
Is there any way with tice.h to get calc time in ms like System.currentTimeMillis(); in java ?

Thx ^^

Edit : The only one way i found is rtc_Time() but it's seconds, not ms :(

Edit #2 : Ik delay(ms) but this freeze the calc so it's not very noice

**Comment by jacobly0** [comment]
The calculator hardware does not track real time to ms precision so no it is not possible.  If you just want a ms counter you can just use the timers in `tice.h`.

**Comment by runer112** [comment]
This functionality is possible to provide if we set up one of the timers with this purpose in mind. I don't think we should discount this.

**Comment by DuCouscous** [comment]
Thank you for help ^^

**Comment by mateoconlechuga** [comment]
I disagree with Runer112. You would still need a function which starts the timer, and even then all you are making is very small wrappers around the already existing timer functions.

**Comment by runer112** [comment]
The function to start the timer can be called from the startup code. And sure, it's only small wrappers, but that's kind of the point of system/standard libraries.

**Comment by mateoconlechuga** [comment]
@runer112: There isn't a standard, non-implementation defined C function to get the system time in milliseconds though. Why not just let people use the already existing timer functions? There's no point in starting a random timer on program start.

**Comment by runer112** [comment]
There isn't a standard C function, sure, but every OS provides one. And if we'd like to build up C++ support, then chrono needs it.

**Comment by mateoconlechuga** [comment]
wut.

**Comment by runer112** [comment]
I guess a better argument is for implementing https://en.cppreference.com/w/c/chrono/clock, which is part of the C standard library.

**Comment by mateoconlechuga** [comment]
Yeah we should probably implement that rather than just returning -1. But what timer do we use? And what if the user starts to use it?

**Comment by runer112** [comment]
Unless we want to only be able to count time for ~90 seconds, we'll have to use two timers, probably timers 1 and 2. If the program uses them for other purposes, there's really nothing we can do. `clock` (and any related functions) would simply produce garbage.

**Comment by runer112** [comment]
@DuCouscous Good news, [clock()](https://en.cppreference.com/w/c/chrono/clock) has been implemented! In combination with [CLOCKS_PER_SEC](https://en.cppreference.com/w/c/chrono/CLOCKS_PER_SEC), you can now calculate time intervals with precision down to about a tenth of a millisecond.
