### ISSUE TITLE
Key Press Issue

### ISSUE THREAD

**Issue by DuCouscous** [CE-Programming/toolchain#322]
When I press like Key "mode", that do the action of "clear" key pressed, and that with every key (2 with left, 6 with right, etc.), why ?

I tried with kb_data & kb_isdown but it bug :(

EDIT : It's like if all kb_Data were the same, like if it wasn't mattering the bit i was using

**Comment by adriweb** [comment]
- Can you share [the part of] your C code that triggers the issue?

- Which calculator model do you have exactly?

- Which hardware revision/datecode is it? (On the back of the calculator, it's the letters/numbers to the right of the serial number, for instance `L-0321S`.

**Comment by DuCouscous** [comment]
kb_IsDown(kb_KeyRight) just even that bug :(

Calc : TI 83 Premium CE Os v5.4.0.0034
L-0515A

It's probably my fault like I use too much memory 😅

**Comment by adriweb** [comment]
Ok so it's probably something wrong in the code somewhere then... if you can post it, we'll need the full file! (For instance on pastebin.com or similar)

**Comment by DuCouscous** [comment]
Here is the full code (1 .c and 3.h) https://hastebin.com/jizeyeqesi.cpp

I know it's not good to put functions in .h but as i said in hastebin i'm a beginner :D

**Comment by mateoconlechuga** [comment]
You need to execute the `kb_Scan` function before reading the state of the keypad. See the examples.
