### ISSUE TITLE
delay function not working

### ISSUE THREAD

**Issue by randomguy70** [CE-Programming/toolchain#332]
So I installed the newest release of the toolchain yesterday, and built my snake program that I was working on before just fine. However, the delay() function that I am using to control the speed of the game seems to not be working; instead, it just stops the game and the program freezes, compelling me to do a RAM reset. Otherwise, the new release seems to be great! P.S. The delay function freezes when the unit16_t delay parameter is > 0, if the parameter is == 0, then it doesn't freeze.

**Comment by runer112** [comment]
Hmm... Are you using the timers at all, especially timer 2? `delay()` has always used timer 2, but previously it would set up the timer with each invocation. So it happened to be okay if you used timer 2 but not at the same time that you were using `delay()`. However, now timer 2 is set up once on program startup, and it's used for `delay()` and all the new timing functions. So if you ever use timer 2 yourself, all these functions will stop working properly.

**Comment by mateoconlechuga** [comment]
Do you have a ZIP file that we can inspect?

**Comment by randomguy70** [comment]
[snake 2.zip](https://github.com/CE-Programming/toolchain/files/7148224/snake.2.zip)
and no, I am not using the timers to my knowledge.

**Comment by runer112** [comment]
Found the bug with help from @mateoconlechuga. I had incorrectly documented the register outputs of `clock()`, which is used by `delay()` and led me to implement `delay()` slightly incorrectly.

**Comment by randomguy70** [comment]
ok. Thank you!!!

**Comment by mateoconlechuga** [comment]
This has now been fixed in a new release v9.2.1 -- mac binaries will be available shortly, they need to be signed though.
