### ISSUE TITLE
fileioc issues with old programs using new libs

### ISSUE THREAD

**Issue by randomguy70** [CE-Programming/toolchain#334]
So I noticed that the newest release of HexaEdit (as of 1 hour ago) works fine with the old libraries that were the latest at the time of its release, but for some reason it has issues with fileioc when using the new clibs.

**Comment by adriweb** [comment]
What exactly is the encountered issue?

**Comment by randomguy70** [comment]
HexaEdit says "unable to resize edit file" on every file i try to open.

**Comment by mateoconlechuga** [comment]
There was a bug where ti_Resize wouldn't work at all -- it's not even a tested function at all lol.
