### ISSUE TITLE
Minimal example for `usbdrvce`?

### ISSUE THREAD

**Issue by Breq16** [CE-Programming/toolchain#336]
I'm trying to write a program that makes use of the USB port. I was able to compile and run [this example](https://github.com/CE-Programming/toolchain/blob/d75be2d1ea24b2335fa7e1d9eb292768ee73074e/examples/usbdrvce/test/src/main.c) using the `usbdrvce` branch of the toolchain, but I'm struggling to understand the code. It seems like there's a lot of logging output being displayed, and I can't figure out which sections of the code are necessary for USB operation, and which ones are just to test the API or display debug output.

Could you provide an example or just some guidance on the bare minimum required to connect the calculator as a USB device of some descriptor? Say, for instance, a HID keyboard, or a serial port?

**Comment by jacobly0** [comment]
That example doesn't test device mode at all, the first step is the just pass the descriptors you want to `usb_Init`.
