### ISSUE TITLE
Can you help me with this error?

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [CE-Programming/toolchain#346]
Hey yall, so anyways when I try to compile an example in the toolchain It gives me a error. the error says: C:\CEdev\bin\fasmg.exe' is not recognized as an internal or external command,
The filename, directory name, or volume label syntax is incorrect. or something like that so can you guys help me please!

**Comment by adriweb** [comment]
Is the program `fasmg.exe` actually present in the tolder `C:\CEdev\bin`? Was it mistakenly blacklisted/quarantined by an anti-virus of some sort? Make sure it's whitelisted.

**Comment by NeoGeoFreak2004** [comment]
`the program fasmg.exe is not present in the folder C:\CEdev\bin , idk if it got blacklisted by a antivirus?

**Comment by adriweb** [comment]
What else is in that folder?

And check windows defender and your antivirus black list, then.

**Comment by mateoconlechuga** [comment]
The install guide recommends disabling your antivirus scanner on Windows. Closing issue.
