### ISSUE TITLE
P3 randomly raising Internal Error (0x83BAF1)

### ISSUE THREAD

**Issue by Moi78** [CE-Programming/toolchain#347]
Some times it works, some times it don't. That's annoying to rely on a random raising error.

![image](https://user-images.githubusercontent.com/19874518/148647917-8d2ba2d9-eaec-4ac2-acb4-8c4d14beb5d9.png)
Here is the only output I have. I tried to get more details but didn't find anything.

**Comment by adriweb** [comment]
You have an extremely old toolchain (with an obsolete and unsupported compiler), please update to the latest one.
Make sure you migrate your makefile(s) like the toolchain examples.
