### ISSUE TITLE
`os_PrgmEditor` a built-in program editor

### ISSUE THREAD

**Issue by Overload02** [CE-Programming/toolchain#349]
Since program execution is already possible through the toolchain, I believe it will be required to incorporate the program editor into the toolchain. In other words, the toolchain should be capable of launching the TI program editor.

I believe the syntax should be somewhat similar to `os_RunPrgm(const char *prgm, void *data, size_t size, os_runprgm_callback_t callback)`. So it should look something like `os_PrgmEditor(const char *prgm, os_runprgm_callback_t callback)`. where `prgm` is the program name that wants to be executed and `callback` should be similar to `os_RunPrgm` Whereas it returns back to the Program it was executed from.

Feel free to change the function name.

**Comment by mateoconlechuga** [comment]
No. Implement this yourself, this is not the responsibility of the toolchain.
