### ISSUE TITLE
Building from source cannot find fasmg-ez80

### ISSUE THREAD

**Issue by ordelore** [CE-Programming/toolchain#350]
I'm trying to build from source on an M1 MBP to experiment with getting the toolchain to build and run. This is with the latest commit from master.
When I run `make -j`, I get the following error. I have fasmg and ez80-clang accessible via my PATH, so I do not believe the error is on my end. Am I correct in assuming that only the ez80-clang and fasmg executables need to be accessible via the PATH?
If this is an example of Rosetta rearing its ugly head, then I'll wait and try again later.
```
clang version 14.0.0 (https://github.com/jacobly0/llvm-project b1303ec02a1932c74c306658339d3386d7f46b47)
Target: ez80
Thread model: posix
InstalledDir: /Users/ordelore/bin
flat assembler  version g.jje9
1 pass, 0 bytes.
make[1]: *** No rule to make target `release'.  Stop.
make[1]: *** No rule to make target `release'.  Stop.
make: *** [convbin] Error 2
make: *** Waiting for unfinished jobs....
make: *** [convimg] Error 2
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [convfont] Error 2
cp: fasmg-ez80/commands.alm: No such file or directory
cp: fasmg-ez80/ez80.alm: No such file or directory
cp: fasmg-ez80/ez80.inc: No such file or directory
cp: fasmg-ez80/tiformat.inc: No such file or directory
make[1]: *** [all] Error 1
make[1]: Nothing to be done for `all'.
make: *** [fasmg] Error 2
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
```

**Comment by adriweb** [comment]
You should be able to find more precisely what's wrong with `make -d`. Can you copy/paste what it says with that around the `make[1]: *** No rule to make target `release'.  Stop.` ?

**Comment by adriweb** [comment]
Turns out you may simply not have cloned the repo recursively (with the submodules).
Try this first: `git submodule update --init --recursive` then build again.

**Comment by ordelore** [comment]
Thanks for the help! That fixed my problem. That's what I get for not reading the whole docs.
Building still brings up the "not enough memory" error that plagues M1 builds, so I'll shelve my own experimentation until later.

**Comment by adriweb** [comment]
Depending on the error, it may not be M1-related, check this out: https://github.com/CE-Programming/toolchain/discussions/344
