### ISSUE TITLE
Get a fatal error when compiling a graphx example.

### ISSUE THREAD

**Issue by DinoNuggies4665** [CE-Programming/toolchain#362]
Whenever I compile the `sprite` example in the `graphx` example folder, I get this error:
`
C:\CEdev\examples\graphx\sprites>make
[compiling] src\main.c
C:/CEdev/examples/graphx/sprites/src/main.c:5:10: fatal error: 'gfx/gfx.h' file not found
#include "gfx/gfx.h"
         ^~~~~~~~~~~
1 error generated.
make: *** [obj/src/main.c.src] Error 1
`
I saw the YAML file in the `gfx` folder, am I supposed to do something with it to convert the images? Or is something not installed right?

**Comment by adriweb** [comment]
You have to do this first: make gfx

**Comment by DinoNuggies4665** [comment]
Thank you!

**Comment by DinoNuggies4665** [comment]
I couldn't find anything about that in the documentation though.

**Comment by adriweb** [comment]
Hmm, indeed.

Although as we like to say, source codes are the best docs, and the test scripts [do have it](https://github.com/CE-Programming/toolchain/blob/master/.github/workflows/make.yml#L174) :D

**Comment by DinoNuggies4665** [comment]
I agree, I learn a lot from source code, however it's not always very fun to read haha.
