### ISSUE TITLE
TI-84 stuck off after running program

### ISSUE THREAD

**Issue by kdkasad** [CE-Programming/toolchain#364]
I created a program in C using the graphx library, and when the calculator is turned off after running the program, it refuses to turn back on until the `reset` button on the back of the calculator is pressed. To clarify: I'm talking about running the program, exiting it, and then turning the calculator off. The program has completely exited by the time I turn it off.

My program doesn't store any information using variables or anything like that, so I'm not sure why this problem would take effect after the program has exited.

Also, this same issue occurs in CEmu using a different ROM version, so it's likely not a hardware issue and doesn't seem to be a bug in the ROM either.

The program sources are here [on my git server](https://git.kasad.com/ti-wordle/tree/?id=d81ed36351ea52e2dc9311cc9cd4d1adac9d1d74) (at commit d81ed36).

**Comment by jacobly0** [comment]
Well yeah, you can't turn on the calc with the rtc disabled.

**Comment by kdkasad** [comment]
> Well yeah, you can't turn on the calc with the rtc disabled.

Oh, thank you! I thought the RTC enable/disable was something that was supposed to be done before/after using, like the `gfx_Begin()` and `gfx_End()` functions.

Also thanks for the very quick reply!

**Comment by jacobly0** [comment]
RTC is the real time clock, which you can see on the bottom of the mode menu.

**Comment by kdkasad** [comment]
> RTC is the real time clock, which you can see on the bottom of the mode menu.

Yes, I realize what it means, but I had no idea that it  would prevent the calculator from booting. Maybe a warning should be added to the [`rtc_Disable()` documentation](https://ce-programming.github.io/toolchain/headers/tice.html#c.rtc_Disable)?

Anyways, my problem is solved now. Thanks again!
