### ISSUE TITLE
sprintf fails with floats >= 0x800000

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/toolchain#367]
sprintf returns "00000000000000000000002147483648" when using `sprintf(buf, "%f", num)` with num >= 8388608 (0x800000).
I think this line is the problem: https://github.com/CE-Programming/toolchain/blob/master/src/std/shared/printf.c#L355

**Comment by PeterTillema** [comment]
After looking at the source code, I figured I had to include `float.h` to limit the amount of zeroes displayed. That doesn't solve the problem unfortunately.

**Comment by mateoconlechuga** [comment]
Fixed with 1aaa182a411d380dbff7e3427e9e57d76dea30a2, the maximum is now with an exponent value of 41... which should be enough for most things, and will return "oor" (out of range) in that scenario.
