### ISSUE TITLE
Hang when running some code

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/toolchain#368]
This code ([zip](https://usercontent.irccloud-cdn.com/file/dpfB1fXL/printf-bug-hang.zip)) hangs when compiled with the `feature/printf` branch. It's either 64 bit ints or the compiler :)

**Comment by jacobly0** [comment]
Doesn't repro on master.

**Comment by mateoconlechuga** [comment]
It's not supposed to repro on master. It repros on `feature/printf` as the description says.
