### ISSUE TITLE
process_begin: CreateProcess(NULL, cedev-config --makefile, ...) failed.

### ISSUE THREAD

**Issue by DuCosucosu** [CE-Programming/toolchain#380]
Hello I have this issue with the programming toolchain...
I got make, I got the hello world example, and I can't build

The full error :
`process_begin: CreateProcess(NULL, cedev-config --makefile, ...) failed.
makefile:16: pipe: No error
make: *** No targets.  Stop.`

**Comment by adriweb** [comment]
What OS are you on exactly and how are you running make, exactly?

**Comment by adriweb** [comment]
Ok apparently it was a path issue - see the instructions on https://ce-programming.github.io/toolchain/static/getting-started.html
