### ISSUE TITLE
How do I add the vector header files in the toolchain?

### ISSUE THREAD

**Issue by tarneaux** [CE-Programming/toolchain#381]
I just read [363](https://github.com/CE-Programming/toolchain/issues/363) about the missing vector headers in C++.
I really do need to use vectors. I've googled around for the past 20 mins but can't seem to find anything... How do I add it to the toolchain? (maybe other libs too if it doesn't make the bundle too large)
Thanks

**Comment by mateoconlechuga** [comment]
Why do you "really need to use vectors"? It's not going to make your code faster or better.

Use something like [tinystl](https://github.com/mendsley/tinystl) if you really need them.
