### ISSUE TITLE
Compiler error with `ti_GetGCBehavior` using C++ with toolchain v10.0

### ISSUE THREAD

**Issue by Captain-Calc** [CE-Programming/toolchain#385]
The bug can be replicated by putting the following code into a CE program's `main` file:
```#include <fileioc.h>
#include <graphx.h>

void setup_graphx()
{
  gfx_Begin();
}

int main(void)
{
    ti_SetGCBehavior(&gfx_End, &setup_graphx);
    return 0;
}
```

If the file is saved as a C++ file, the compiler will throw an error: `candidate function not viable: no known conversion from 'void (*)()' to 'void (*)()' for 2nd argument` on `ti_GetGCBehavior`. If the file is saved as a C file, the program will compile.

**Comment by mateoconlechuga** [comment]
https://wiki.sei.cmu.edu/confluence/display/cplusplus/EXP56-CPP.+Do+not+call+a+function+with+a+mismatched+language+linkage

**Comment by mateoconlechuga** [comment]
@jacobly0 appears to be a race condition - swapping the `include <graphx.h>` and `include <fileioc.h> lines in main.cpp and running the following yields odd results: https://www.irccloud.com/pastebin/MPX0Sm7M/

**Comment by jacobly0** [comment]
This has been fixed in the compiler.
