### ISSUE TITLE
Include SDLC in coding guideline

### ISSUE THREAD

**Issue by Overload02** [CE-Programming/toolchain#394]
What is the SDLC?
_SDLC stands for Software Development Life Cycle. It is also known as the Software Development Process_.

Most new developers are unfamiliar with the process of creating a program or project. I believe that including information in the guidelines on how to develop and release a program over time would be extremely beneficial!

**Comment by mateoconlechuga** [comment]
What on earth does that have to do with the toolchain?

**Comment by adriweb** [comment]
I doubt this is really needed for the kind of projects people do on the CE.
We're offering guidelines and good habits in general, we're not trying to make them developers feel like they're trapped under a set of strict development process rules.

**Comment by mateoconlechuga** [comment]
"You must use AGILE and SAFE with weekly sprints and scrum meetings"
