### ISSUE TITLE
Oxygen

### ISSUE THREAD

**Issue by Overload02** [CE-Programming/toolchain#405]
I've been working on Oxygen for the past year now! It's a huge powerful library that uses the CE toolchain. I really would love to include Oxygen in the [CE programming github section](https://github.com/CE-Programming). 

I personally don't think it should be included with the toolchain like fontlib because I feel like Oxygen and the toolchain are two different things. I think Oxygen should be viewed as the "gdk" of [cairo](https://github.com/freedesktop/cairo), in this case the gdk of the toolchain.  

Oxygen is still under development but keep in mind if it ends up getting included in the github "section/group" I would gladly keep it up to date and maintain it!

You can read more about the features [here](https://www.cemetech.net/forum/viewtopic.php?t=18783&highlight=) , please keep in mind that the library is still under development and there may be some few typos' here and there! 

Edit: There was some chat about just including Oxygen in the toolchain documentation. Which I find very great and all but my goal with Oxygen is to help developer make powerful programs/application ... without all the hustle of building it from scratch ... which is very common in C/C++ thus the creation of different powerful libraries for example gdk, gtk, and cairo.

**Comment by mateoconlechuga** [comment]
I wouldn't have an issue with it as long as the API makes sense and we can review it

**Comment by mateoconlechuga** [comment]
So I have looked at the code and API for Oxygen, and it is rather.... Perhaps you should read the Coding Guidelines? 

https://ce-programming.github.io/toolchain/static/coding-guidelines.html

**Comment by LogicalJoe** [comment]
There is also [OPTIX_3](https://github.com/epsilonfive/OPTIX_3).  Last I was aware this particular repo is slightly outdated, hopefully that can be remedied soon.

**Comment by Overload02** [comment]
> So I have looked at the code and API for Oxygen, and it is rather.... Perhaps you should read the Coding Guidelines?
> 
> https://ce-programming.github.io/toolchain/static/coding-guidelines.html

Hello, Mateo. Could you please explain what is wrong with the API? and how it does not follow the coding guidelines?

**Comment by commandblockguy** [comment]
What even is "a" GTK, anyway?
The GTK widget toolkit certainly exists, but that's the name of a specific project, not a general name for libraries that do the same thing that it does.

A wide range of features is not necessarily a benefit in this case - we usually want each library to do one specific thing, so that it's clear which library you want to use to accomplish a particular task, and so that we don't have to maintain two separate functions for doing the same thing.

I can't say much more without being able to see the code, or at least the header files with the API in them.

**Comment by mateoconlechuga** [comment]
I have looked at the code and API.

I'm not sure it is something that should be used by anyone in this state. Besides the numerous (countless) bugs and memory leaks, the API doesn't make much sense. What is a user? What is a notification? Why do debug messages flood the user program? It also arbitrary draws things without regard to the current user context, such as swapping buffers. There's also no testing infrastructure in place, and no notion of what this library is actually *for* - is it just a "here's some random functions that you can use to do various things"? It doesn't really make much sense to me at least.

There's also these ridiculous batch file scripts being used in place of the makefile (and copying the entire library??) basically making the makefile useless in practice.

**Comment by mateoconlechuga** [comment]
Closing for now until significant work is made.

**Comment by mateoconlechuga** [comment]
I don't mean to be too harsh, just trying to be objective.

Honestly if you pull out just the GTK windowing and GUI things, that might be a better library for users? That stuff is pretty nice.

The problem with adding a bunch of functionality that makes things "easier" for users is that it doesn't actually - they need to first learn the toolchain, and then learn how to use the library, and then learn how to use the library well - and if they don't, they'll end up just creating another library on top of Oxygen to fix their lack of knowledge unfortunately.
