### ISSUE TITLE
Timer ChkInterrupt and AckInterrupt Documentation error.

### ISSUE THREAD

**Issue by matthewkeller36** [CE-Programming/toolchain#406]
Documentation for both checking and acknowledging interrupts state that the mask uses `TIMER_RELOADED`. When checking for reload on timers other than timer 1, using `TIMER_RELOADED` does not check properly. For example, to check reload interrupt for timer 3, I must use `timer_ChkInterrupt(3, TIMER3_RELOADED)` rather than `timer_ChkInterrupt(3, TIMER_RELOADED)` while acknowledging it does not require specifying the timer mask.

**Comment by mateoconlechuga** [comment]
It's not a documentation error. Are you using the latest release?

**Comment by matthewkeller36** [comment]
Wow, this was a very embarrassing mistake. I had two timers running together (1 and 3) and thought that may have been causing an issue, but neglected to realize one timer was reloading within the timeframe that the other would. I forgot to negate the `timer_ChkInterrupt` thus since the timer had already reloaded it would obviously return true. Mistake on my part, not an issue.

**Comment by mateoconlechuga** [comment]
Haha at least it is working :) Good luck on the rest of the project!
