### ISSUE TITLE
Add Support for TI's Characters in Default Font

### ISSUE THREAD

**Issue by merthsoft** [CE-Programming/toolchain#408]
I wanted to draw the left/right solid arrows that TI has in their font. I did the following:
```C
gfx_SetTextXY(0, 0);
gfx_PrintChar((char)195);
```
And it printed garbage. Mateo says "graphx just defines the ascii characters \ so 7bits of char".

It would be really cool to be able to access the full range of TI's font in the default font and support it for other fonts too.

**Comment by drdnar** [comment]
"Other fonts"? What do you mean?

**Comment by merthsoft** [comment]
I have not yet looked into how fonts work, so just assumed they'd be the same. If they're not--disregard!

**Comment by mateoconlechuga** [comment]
theoretically this is now possible with fontlibc - so closing the issue for now :)
