### ISSUE TITLE
Question: Is there a way to prevent a key from being continuously scanned when it is held down?

### ISSUE THREAD

**Issue by l2vy7** [CE-Programming/toolchain#412]
I've been testing the CE toolchain for a bit, and found the key scanning thing a bit hard to use.
When I press a key and hold it down, it continuously scans the key until it's released, and I can't find a way for it to only scan it once and fire it again when the key is pressed again.

I have read a bit through the source code and tried ```kb_SetMode(1)```, but it didn't fix the issue.

This is my current code:

```cpp
#include <sys/lcd.h>
#include <sys/power.h>
#include <keypadc.h>
#include <string.h>
#include <stdlib.h>
#include <ti/screen.h>
#include <ti/getcsc.h>
#include <sys/rtc.h>
#include <sys/util.h>
#include <sys/power.h>

void getKey();

void rect(int color, int w, int h);
void fillscreen(int color);

void rect(int color, int w, int h) {
    memset((void*)lcd_Ram, color, (w*h*2));
}

void fillscreen(int color) {
    memset((void*)lcd_Ram, color, LCD_SIZE);
}

int main(void)
{
    kb_SetMode(1);

    os_ClrHomeFull();
    os_ClrLCDFull();

    fillscreen(0);

    os_FontSelect(os_SmallFont);

    os_SetDrawBGColor(0x0000);
    os_SetDrawFGColor(0xFFFF);

    uint24_t fh = os_FontGetHeight();

    rect(0x0000, LCD_WIDTH, fh);

    os_FontDrawText("-", 0, 0);

    bool inMenu = false;

    int minIndex = 0;
    int compIndex = minIndex;
    int maxIndex = 2;

    uint8_t level = lcd_BacklightLevel;

    kb_key_t key;

    do
    {
        kb_Scan();
        key = kb_Data[7];

        switch (key)
        {
        case sk_Down:
            if (inMenu == false) {
                os_SetDrawBGColor(0x0000);
                os_FontDrawText("^", 0, 0);
                os_FontDrawText("Power", 0, fh);
                os_FontDrawText("Brightness", 0, fh * 2);
                compIndex = minIndex;
                inMenu = true;
            }
            if (compIndex < maxIndex) {
                compIndex++;
            } else if (compIndex == maxIndex) {
                compIndex = minIndex;
            }
            switch (compIndex) {
                case 0:
                    os_SetDrawBGColor(0xFFFF);
                    os_SetDrawBGColor(0x0000);
                    os_SetDrawFGColor(0xFFFF);
                    os_FontDrawText("^", 0, 0);
                    os_FontDrawText("Brightness", 0, fh * 2);
                    os_SetDrawBGColor(0xFFFF);
                    os_SetDrawFGColor(0x0000);
                    os_FontDrawText("Power >", 0, fh);
                    break;
                case 1:
                    os_SetDrawBGColor(0xFFFF);
                    os_SetDrawBGColor(0x0000);
                    os_FontDrawText("^", 0, fh);
                    os_FontDrawText("Power", 0, fh);
                    os_SetDrawBGColor(0xFFFF);
                    os_SetDrawFGColor(0x0000);
                    os_FontDrawText("Brightness >", 0, fh * 2);
                    break;
                default:
                    break;
            }
            break;
        case sk_Up:
            if (inMenu == true) {
                fillscreen(0x0000);
                os_SetDrawBGColor(0x0000);
                os_FontDrawText("-", 0, 0);
                inMenu = false;
            }
            break;
        case sk_Right:
            switch (compIndex) {
            case 0:
                boot_TurnOff();
                break;
            case 1:
                if (level < 255) {
                    lcd_BacklightLevel += 1;
                    level += 1;
                } else {
                    lcd_BacklightLevel = 0;
                    level = 0;
                }
                break;
            default:
                break;
            }
            break;
        default:
            break;
        }

    } while (kb_Data[1] != kb_2nd);

    return 0;
}
```

**Comment by commandblockguy** [comment]
"Scanning" just means checking which keys are currently held down - if you're not scanning the keypad, you can't tell when it's been released. The toolchain does not have a mechanism for detecting when a key first gets pressed, only whether it's currently pressed.

There's a few things that you can do to only process each keypress once:
The easiest is to just have a loop that waits for the key to be released again before doing anything else. This is easiest to set up, but causes a noticeable delay in some cases.
The other option would be to store what keys were pressed, and only process a key if it was pressed this loop but not last loop. This is a bit more complicated, but is closer to what you want to do.

**Comment by l2vy7** [comment]
> "Scanning" just means checking which keys are currently held down - if you're not scanning the keypad, you can't tell when it's been released. The toolchain does not have a mechanism for detecting when a key first gets pressed, only whether it's currently pressed.
> 
> There's a few things that you can do to only process each keypress once: The easiest is to just have a loop that waits for the key to be released again before doing anything else. This is easiest to set up, but causes a noticeable delay in some cases. The other option would be to store what keys were pressed, and only process a key if it was pressed this loop but not last loop. This is a bit more complicated, but is closer to what you want to do.

Thank you. I have tried the first option, but it seems the way I did it didn't work as planned.
I will try the second option.

**Comment by zwassall-globus** [comment]
If you want the input method in your program to feel like the OS, you can simply use the OS key input function `os_GetCSC`. This has the behavior of key codes only being triggered once per press, except for the arrow keys and DEL which have timer-based repeat behavior (like in the OS).

**Comment by runer112** [comment]
If you want the input method in your program to feel like the OS, you can simply use the OS key input function os_GetCSC. This has the behavior of key codes only being triggered once per press, except for the arrow keys and DEL which have timer-based repeat behavior (like in the OS).

**Comment by mateoconlechuga** [comment]
This exact question is answered in the docs for keypadc: https://ce-programming.github.io/toolchain/libraries/keypadc.html#helpful-key-dection
