### ISSUE TITLE
demo2 doesn't compile

### ISSUE THREAD

**Issue by metawops** [CE-Programming/toolchain#42]
Downloaded the latest toolchain on my iMac (macOS Sierra 10.12.1), installed the Wine Devel 1.9.23 .pkg and set up the environment variables.
Works fine so far. I was able to successfully build the demo0 and the demo1, transfer them to my TI-84 Plus CE-T and run them there via `Asm(prgmDEMO0` and `Asm(prgmDEMO1`. 😃 

The demo2, however, can't be compiled. Here's the output of make.exe:
```
Z:\Users\stefan\CEdev\examples\demo_2\src\main.c
Z:\USERS\STEFAN\CEDEV\EXAMPLES\DEMO_2\SRC\MAIN.C	(22,42) :	WARNING (197) No function prototype "lcd_GetBacklightLevel" in scope
Z:\USERS\STEFAN\CEDEV\EXAMPLES\DEMO_2\SRC\MAIN.C	(26,25) :	WARNING (197) No function prototype "lcd_SetBacklightLevel" in scope
Z:\USERS\STEFAN\CEDEV\EXAMPLES\DEMO_2\SRC\MAIN.C	(31,25) :	WARNING (197) No function prototype "lcd_SetBacklightLevel" in scope
Z:\USERS\STEFAN\CEDEV\EXAMPLES\DEMO_2\SRC\MAIN.C	(34,24) :	WARNING (197) No function prototype "lcd_SetBacklightLevel" in scope
ConvPNG 5.5 by M.Waltz

Converted icon 'iconc.png'
Linking...
WARNING (724) --> Symbol _lcd_SetBacklightLevel (obj\main.obj) is not defined.
WARNING (724) --> Symbol _lcd_GetBacklightLevel (obj\main.obj) is not defined.


SPACE ALLOCATION:
=================

Space                     Base         Top      Size      Used    Unused
------------------ ----------- ----------- --------- --------- ---------
RAM                   D:D1A87F    D:D1AA71   300000H      1F3H   2FFE0DH
                                          (  3145728       499   3145229)

ERROR: Object file(s) deleted because of option unresolved=fatal.
Consult bin/DEMO2.map for more information.
make: *** [bin/DEMO2.hex] Error -1
```

Both functions have no prototype in the main.c file. Is that meant to be so?

**Comment by adriweb** [comment]
Woops - indeed, looks like `lcd_SetBacklightLevel` got removed at some point (replaced by [a simple define](https://github.com/CE-Programming/toolchain/blob/e0a9732c89fd053179433cffcd99ab5a603e3b49/CEdev/include/lib/ce/tice.h#L106)).

[This fixed code](https://github.com/CE-Programming/toolchain/blob/81b330d5a66630cb6c570136677a3ec7ed50e735/CEdev/examples/demo_2/src/main.c) seems to work :)

**Comment by MateoConLechuga** [comment]
Hm, I should check these things more often :P Sorry about that.
