### ISSUE TITLE
CreateProcess(NULL, cedev-config --makefile, ...) failed. Error

### ISSUE THREAD

**Issue by idkwebdev** [CE-Programming/toolchain#421]
When I use the `make` command on an example folder I get the following error.

```
C:\CEdev\examples\hello_world> make
process_begin: CreateProcess(NULL, cedev-config --makefile, ...) failed.
make: *** No targets.  Stop.
```

In this case I'm using `make` with the `C:\CEdev\bin\` folder in as a PATH variable, but the same issue occurs when using `cedev.bat`.

I'm using Windows 10 and the latest version of the CE toolchain.

**Comment by adriweb** [comment]
That means it couldn't find the cedev-config executable. Are you **_sure_** you followed the steps of the Getting Started guide to correctly setup the PATH?

**Comment by mateoconlechuga** [comment]
Make sure your antivirus (if you have one) hasn't removed binaries just because it feels like it.

**Comment by idkwebdev** [comment]
> Make sure your antivirus (if you have one) hasn't removed binaries just because it feels like it.

I think that may be the problem. Lemme try disable it and get back.

**Comment by idkwebdev** [comment]
It works now! Thanks for the help
