### ISSUE TITLE
Typo on ti/real.h docs page

### ISSUE THREAD

**Issue by Blackgaurd** [CE-Programming/toolchain#423]
The description for `os_FloatToReal(float arg)` should be "converts **a** float to real_t" rather than "converts **an** float to real_t".

[link to docs](https://ce-programming.github.io/toolchain/headers/ti/real.html?highlight=real#_CPPv414os_FloatToRealf)

**Comment by mateoconlechuga** [comment]
You can edit it here and create a pull request if you want: https://github.com/CE-Programming/toolchain/blob/master/src/ce/include/ti/real.h
