### ISSUE TITLE
How to access sprites from appvar files?

### ISSUE THREAD

**Issue by CoolModder** [CE-Programming/toolchain#451]
I've poked through the documentation multiple times, but can't find a way to get sprites from appvars.  Is there a way to access these sprites?

**Comment by adriweb** [comment]
There are several appvar-based sprites examples here: https://github.com/CE-Programming/toolchain/tree/master/examples/library_examples/graphx

**Comment by CoolModder** [comment]
Thank you! Have a nice day.
