### ISSUE TITLE
Smaller Text Support

### ISSUE THREAD

**Issue by CoolModder** [CE-Programming/toolchain#452]
Is there a way to make smaller text? Scale one is too big for the space I am trying to fit it in (Default Font.) Results in:
![image](https://github.com/CE-Programming/toolchain/assets/132532001/b369a216-b5a4-42e3-be6f-dbaad106b605)
Text Code:
```
	if (page == 0)
	{
		gfx_TransparentSprite(up_add, 140, 78);
		gfx_SetTextXY(170, 78);
		gfx_PrintString("Addition Symbol X");
		gfx_PrintUInt(addcount, length(addcount));

		gfx_SetTextXY(170, 88);
		gfx_PrintString("+1 Equation Per Click");
		gfx_SetTextXY(170, 98);
		gfx_PrintString("Wait, there's an upgrade?");
	}
```

**Comment by runer112** [comment]
There's only that one default font. You'd have to provide your own narrower font. You could either supply it to GraphX via [`gfx_SetFontData`](https://github.com/CE-Programming/toolchain/blob/22f41bd7871efeb041859c9cb3d673d3fa4f9f02/src/graphx/graphx.h#L1497-L1508) and [`gfx_SetFontSpacing`](https://github.com/CE-Programming/toolchain/blob/22f41bd7871efeb041859c9cb3d673d3fa4f9f02/src/graphx/graphx.h#L1525-L1532) or use the more advanced [fontlibc](https://github.com/CE-Programming/toolchain/blob/22f41bd7871efeb041859c9cb3d673d3fa4f9f02/src/fontlibc/fontlibc.h) ([examples](https://github.com/CE-Programming/toolchain/tree/22f41bd7871efeb041859c9cb3d673d3fa4f9f02/examples/library_examples/fontlibc)).

**Comment by CoolModder** [comment]
Thank you!
