### ISSUE TITLE
Ints Not Displaying Properly With Printing

### ISSUE THREAD

**Issue by CoolModder** [CE-Programming/toolchain#455]
![image](https://github.com/CE-Programming/toolchain/assets/132532001/91aa6d0d-1c85-451f-a1f1-0afe920a0aa7)
It appears this number is not displaying properly. The actual price is fine, but the formula does not display properly on screen.
(uint64_t values)
```	
uint8_t length(uint64_t num)
{
	uint8_t len = 1;
	uint64_t i = num;
	if (i > 0) {
		for (len = 0; i > 0; len++) {
			i = i / 10;
		}
	}
	return len;
}
gfx_PrintUInt(15 * pow(11.0 / 100.0, studentcount), length(15 * pow(11.0 / 10.0, studentcount)));
```

**Comment by mateoconlechuga** [comment]
What value are you using / what is the expected output?

**Comment by commandblockguy** [comment]
I think you have an extra zero in the price formula - as shown in the screenshot (11 / 100)^5 is 0.0000161051, so (11 / 100)^5 × 125 is 0.00201314, which gets rounded down to zero.

Additionally, if you don't want to pad the output with leading zeroes, you can just use 1 for the second argument - no need to calculate the length yourself.

**Comment by CoolModder** [comment]
Studentcount is the power (Increase price by 10 percent each buy.)

**Comment by CoolModder** [comment]
Thank you!

**Comment by mateoconlechuga** [comment]
Also shouldn't it be `i > 9`

**Comment by CoolModder** [comment]
> Also shouldn't it be `i > 9`

It works fine. Was doing: 

> I think you have an extra zero in the price formula - as shown in the screenshot (11 / 100)^5 is 0.0000161051, so (11 / 100)^5 × 125 is 0.00201314, which gets rounded down to zero.
