### ISSUE TITLE
<fileioc.h> ti_Write Crash

### ISSUE THREAD

**Issue by vitalash1** [CE-Programming/toolchain#461]
On OS 5.4.0.0034 this program consistently crashes with my reproduction steps involving filling the RAM.
```
#include <fileioc.h>
#include <stdint.h>

#define size_to_write 37924
uint8_t data[size_to_write];

int main() {
    uint8_t handle = ti_OpenVar("BUGVAR", "w", OS_TYPE_PRGM);
    ti_Write(data, 1, size_to_write, handle);
    ti_Close(handle);
    return 0;
}
```
![NVIDIA_Share_pCSUARrJuu](https://github.com/CE-Programming/toolchain/assets/48282719/8fcdb880-898d-4b4d-ba17-be13a87bac33)

My CEMU version is
![image](https://github.com/CE-Programming/toolchain/assets/48282719/7b5113be-5cbc-4ead-97ad-85e06b8b992d)

Reproduction Steps
- Reload ROM on TI-OS 5.4.0.0034 (Untested with other OS versions.) [Here's a rom for use with CEMU](https://drive.google.com/file/d/15eCC6Fz3uBqFYaLwQNIXhqMLzlBfWjHA/view?usp=sharing)
- Compile the above program (my compiled version of it is AETHER.8xp in the following provided .zip file)
- Download "BugPack.zip" and put "clibs.8xg", "WALDATA1.8xp", and "WALDATA3.8xp" into RAM. As well as that, put in the bug-reproducing program whose code is shown above (pre-compiled as AETHER.8xp inside the zip)
[BugPack.zip](https://github.com/CE-Programming/toolchain/files/13405165/BugPack.zip)
- There should be ~56,000 RAM free. Now, run the compiled reproduction program and note a crash on ti_Write (any code past ti_Write will not be executed I believe, from testing with dbg_printf earlier)

If you do not specifically fill the **ram** with the provided programs WALDATA1.8xp, WALDATA3.8xp, and clibs.8xg, then the crash will not occur.

**Comment by mateoconlechuga** [comment]
thank you for this excellent bug report, I'll look into it tonight :)

**Comment by mateoconlechuga** [comment]
Fixed, new libraries can be downloaded from the [nightly](https://github.com/CE-Programming/toolchain/releases/tag/nightly) page within the hour.

A new library release should be available within the next week or two.
