### ISSUE TITLE
std::initializer_list iterators are unusable

### ISSUE THREAD

**Issue by tari** [CE-Programming/toolchain#462]
The current definitions of `std::initializer_list::begin` and `end` are faulty because they attempt to to convert `_Ep` to `_Ep*`:

```c++
template<class _Ep>                                                                                                                     
    class initializer_list {
    const _Ep __begin;
    size_t    __size;

public:
    const _Ep* begin() const noexcept { return __begin; }
```

This causes a compile error because `__begin` cannot be converted to a pointer to `_Ep`:

```
.../CEdev/include/c++/initializer_list:24:62: error: cannot initialize return object of type 'T *const *' with an lvalue of type 'T *const'
    _EZCXX_INLINE const _Ep* begin() const noexcept { return __begin; }
                                                             ^~~~~~~
```

Making it explicitly take the address of `__begin` (`&__begin`) fixes this. `end` has the same issue and fix.

**Comment by calc84maniac** [comment]
That's a good catch, but isn't the actual problem the type of `__begin` in the first place? Returning a pointer to it doesn't work as a proper iterator.
