### ISSUE TITLE
localtime reports the wrong day on leap years

### ISSUE THREAD

**Issue by TheMiningTeamYT** [CE-Programming/toolchain#469]
On leap years, if you use localtime, tm_mday from the returned struct will be 1 too high until March 1st.
Here's my code:
[time.tar.gz](https://github.com/CE-Programming/toolchain/files/13878418/time.tar.gz)

**Comment by mateoconlechuga** [comment]
Can you please be more descriptive?

**Comment by mateoconlechuga** [comment]
This is now fixed in the latest nightly! Thanks for the report

**Comment by mateoconlechuga** [comment]
Also @TheMiningTeamYT have you used the `asctime` C function before? I imagine it would greatly clean up your code.

**Comment by TheMiningTeamYT** [comment]
As a matter of fact, no. I'll try it sometime.
