### ISSUE TITLE
FATDRVCE allows lowercase chars in filename

### ISSUE THREAD

**Issue by TheMiningTeamYT** [CE-Programming/toolchain#475]
If you create a file/directory using the functions in FATDRVCE (specifically `fat_Create`), you can use lowercase characters in the name. This is illegal for short (non-LFN) filenames on FAT32 (or any other variant of FAT afaik). This results in files/directories that appear, and can be opened either using `fat_OpenFile`, or on Linux (and I presume any other Unix system), but that can not be opened on Windows, as they apparently don't exist.

This also means that filenames are case sensitive. If you attempt to open a file named `file` by opening `FILE`, it won't work if it was created by `fat_Create`.

This could be fixed by converting each character of the filename to uppercase using a `toupper` call before actually creating the file. I noticed poking around in the assembly (`fatdrvce.asm`) that you already have a function for ensuring filenames are legal before using them (`util_get_fat_name`). A few `toupper` calls in there should do it. I'd do it myself and make a pull request if I understood the assembly.

The code I encountered this bug can be found [here](https://github.com/TheMiningTeamYT/TI84CE-Blocks-3D/tree/main). I entered a world, took a screenshot by pressing the window button, and then attempted to open the `shots` folder.

**Comment by mateoconlechuga** [comment]
I believe it should actually be an error if lowercase letters are used. Additionally, I think your code has an issue here: https://github.com/TheMiningTeamYT/TI84CE-Blocks-3D/blob/main/src/usb.h#L6-L8

Note that the callback types have to be specified before including the appropriate header, like in the [example](https://github.com/CE-Programming/toolchain/blob/94681b4c822a525e6fc7f5dc71d7fe3db86f571f/examples/library_examples/fatdrvce/fat_test/src/main.c#L1-L7).

**Comment by TheMiningTeamYT** [comment]
Well, as of now lowercase names are completely allowed.
Throwing an error if lowercase letters are used isn't the best idea IMO because typically (such as on DOS) lowercase letters are converted to uppercase for short file names, rather than being considered invalid entirely.

**Comment by mateoconlechuga** [comment]
I'm trying to decide if it is better to specify what is on the drive though. Having a lowercase name that doesn't actually exist doesn't make much sense? Why do you think the name the user supplies should be modified?

**Comment by TheMiningTeamYT** [comment]
The reason is that it's the typical behavior of operating systems dealing with FAT32 short names. Even operating systems that support LFN names will convert the filename to uppercase (and truncate it to 8.3), then add an LFN entry for the full lowercase filename.

**Comment by mikaey** [comment]
Also -- to quote the FAT32 specification -- "Lower case characters are not allowed."

https://academy.cba.mit.edu/classes/networking_communications/SD/FAT.pdf, section 6.1, page 24

**Comment by TheMiningTeamYT** [comment]
> I've also been experiencing random resets and filesystem corruption, but I'm not sure if that's the libraries fault or my fault. It might be because I'm not calling `msd_Close` in `usb.c`, but that's because with my 16GB SanDisk Cruzer Micro, `msd_Close` causes my calculator to freeze. I might create an issue for that, but I suspect the bug might be specific to this 1 flash drive, since my other spare flash drive that works with my calculator, a 128MB "Nexdisk" that might actually be 20 years old, doesn't encounter that bug. However, the Nexdisk is super slow, the Cruzer is not, and I don't have any other flash drives that work with my calculator, so it is what it is. :(

By the way, should I make an issue about this? About msd_Close causing my calculator to freeze?

**Comment by mateoconlechuga** [comment]
I think you've convinced me - hopefully in your program you can work around it your code for now until I get the time to fix it. Yes, please make another issue and document the drive you are using (maybe an Amazon link too)

**Comment by mateoconlechuga** [comment]
This is fixed now in nightly
