### ISSUE TITLE
msd_Close causes the calculator to freeze with certain flashdrives.

### ISSUE THREAD

**Issue by TheMiningTeamYT** [CE-Programming/toolchain#477]
I think you've convinced me - hopefully in your program you can work around it your code for now until I get the time to fix it. Yes, please make another issue and document the drive you are using (maybe an Amazon link too)

_Originally posted by @mateoconlechuga in https://github.com/CE-Programming/toolchain/issues/475#issuecomment-1922252927_
            
Well then.
If you initialize a USB flash drive using USBDRVCE and `msd_Open` from MSDDRVCE, then try to deinitialize that flash drive using `msd_Close`, with some flash drives, it will freeze and require the calculator to be reset. If you remove the msd_Close call, the calculator will not freeze.
The drive I'm using is a SanDisk Cruzer Micro U3 16GB (something like [this](https://www.amazon.com/SanDisk-Cruzer-Micro-Flash-SDCZ6-016G-A11/dp/B0018Z0PWY/ref=cm_cr_arp_d_product_top?ie=UTF8)) The code I experienced this issue with can be found [here](https://github.com/TheMiningTeamYT/TI84CE-Blocks-3D). As it stands, accessing the flash drive doesn't cause the calculator to freeze, however, if you uncomment the `msd_Close` call in `closeUSB` in `usb.c` and rebuild, the calculator will freeze every time after the drive is accessed, when closeUSB is called.
I personally suspect this error is specific to this 1 ancient flash drive, so if there's anything you'd like me to do, any data you'd like me to collect, let me know.

**Comment by TheMiningTeamYT** [comment]
By the way, I noticed in your list of supported flash drives, you have a SanDisk Ultra 32GB listed. However, when I tried plugging one of my SanDisk Ultra 32GB drives into my calculator, it caused the calculator to stop responding until I unplugged it. I wonder what's up with that. I'm plugging the flash drive directly into my calculator using a USB on the go mini B to full A adapter, if that helps.

**Comment by TheMiningTeamYT** [comment]
Ok update, while attempting to gather some data on what exactly is going on, I discovered that:
A: The file does actually get written to the flash drive successfully and
B: The calculator does reset on it's own after a strangely long time (Possibly minutes -- I didn't catch exactly when it reset)

**Comment by TheMiningTeamYT** [comment]
More updates:
I have an `msd_Close` call in my `USB_DEVICE_DISCONNECTED_EVENT` handler, as shown in the `FATDRVCE` examples. If I remove that, calling msd_Close no longer causes the calculator to hang until you reset, only hang until you unplug the flash drive (which is the same behavior with this flash drive in Cesium) (this is different from the behavior I observed with my SanDisk Ultra. That causes the calculator to hang as soon as it is plugged in, whereas here it's hanging when the flash drive is uninitialized.)

**Comment by mateoconlechuga** [comment]
I have ordered a SanDisk Cruzer Micro U3 16GB and will update this issue with findings once I get it on the 15th

**Comment by mateoconlechuga** [comment]
I tested this on a SanDisk Cruzer Micro U3 and was able to reproduce the issue, determined it was due to the volatile cache sync command that was sent to the MSD - since like zero flash drives support caching and external SSDs generally require you to enable the cache, I just removed it and things work as expected now. I updated the supported list [here](https://ce-programming.github.io/toolchain/nightly/libraries/msddrvce.html#supported-devices).

New libraries: https://github.com/CE-Programming/libraries/releases/latest
