### ISSUE TITLE
Cedev-config: Command not found

### ISSUE THREAD

**Issue by Orbisculating-Flerovium** [CE-Programming/toolchain#481]
I run a Mac and previously was able to make the examples from CE toolchain after some surfing, but when I made one of my projects I got an error. I tried running the examples make again and got the same error:

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C hello_world/ 
make[1]: cedev-config: Command not found
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [hello_world/makefile] Error 2

I also exported the path like this: _export PATH=/~/CEdev/bin:$PATH_ but I still got the bug. I do have an antivirus, but I can still see the file inside the CEdev bin, so that probably isn't the issue. What's more interesting is that when I run the troublesome include line include "_$(shell cedev-config --makefile)_", but edited so it goes from the home directory like "_include $(shell ~/CEdev/bin/cedev-config --makefile)_"
I get it to where it says this:

make: cedev-config: Command not found
make: cedev-config: Command not found
make: cedev-config: Command not found
make: *** No rule to make target `/lib/crt/crt0.src', needed by `bin/PROJECT.bin'.  Stop.

so that it runs the error 3 times. Did I set something up wrong? What happened?

**Comment by adriweb** [comment]
It's not `PATH=/~/CEdev/bin:$PATH` that you have to use, but: `PATH=~/CEdev/bin:$PATH` (or the full path)

**Comment by Orbisculating-Flerovium** [comment]
Thanks. Didn't think that "/" made much of a difference, but evidently it does.
