### ISSUE TITLE
Add x86 please

### ISSUE THREAD

**Issue by DimastyK** [CE-Programming/toolchain#486]

**Comment by SolventMercury** [comment]
Hi!
    
Unfortunately, that isn't really possible because that's not how Assembly languages work. While languages like BASIC, C, Python, etc. are mostly hardware agnostic, assembly dialects are meant to directly expose all the functionality of the processor. The reason we use eZ80 assembly is because the calculator has an eZ80 processor in it - you have to tailor your written assembly to the machine you're writing it for, so nothing else would work.  
  
Let me know if you need any clarifications.

**Comment by adriweb** [comment]
I suppose they were talking about having builds/releases of the toolchain in 32-bit x86.

**Comment by SolventMercury** [comment]
Oh. Oh I completely misunderstood this. My bad

**Comment by DimastyK** [comment]
> I suppose they were talking about having builds/releases of the toolchain in 32-bit x86.

yes, you are right

**Comment by adriweb** [comment]
Id suggest building the compiler and toolchain on your computer then - you can see how the CI (GitHub actions) does it. fasmg has 32bit binaries available IIRC.

**Comment by DimastyK** [comment]
> Id suggest building the compiler and toolchain on your computer then - you can see how the CI (GitHub actions) does it. fasmg has 32bit binaries available IIRC.

how about convimg, convbin? It is x64 too.

**Comment by mateoconlechuga** [comment]
No x86 support. Please build the toolchain yourself using the instructions provided [here](https://ce-programming.github.io/toolchain/static/contributing.html?highlight=building#building-the-ce-toolchain).

**Comment by DimastyK** [comment]
> No x86 support. Please build the toolchain yourself using the instructions provided [here](https://ce-programming.github.io/toolchain/static/contributing.html?highlight=building#building-the-ce-toolchain).
there are no f.king sources. add it or stay lamerz. idiots

**Comment by adriweb** [comment]
The sources are the GitHub repos.
Considering you can't seem to figure that out, you probably shouldn't try doing all this anyway. Learn programming first then come back later.

Also there are no-setup web-only ways to compile/build CE programs in C/C++/ASM, for instance on SourceCoder and the Project Builder.

**Comment by mateoconlechuga** [comment]
> > > No x86 support. Please build the toolchain yourself using the instructions provided [here](https://ce-programming.github.io/toolchain/static/contributing.html?highlight=building#building-the-ce-toolchain).
> > there are no f.king sources. add it or stay lamerz. idiots
The instructions linked provide information that will work on x86 machines. The sources for the components (conving, conving) are available as well inside the toolchain, and will build for x86 if you follow the instructions.
