### ISSUE TITLE
make: cedev-config: No such file or directory (Debian/Raspbian compiling)

### ISSUE THREAD

**Issue by jvan1234** [CE-Programming/toolchain#497]
OS INFORMATION: 
Raspberry Pi 4 Model B Rev 1.4 
Debian GNU/Linux 12 (bookworm) aarch64

When attempting to compile the hello_world example, I get this error when attempting to compile
```
make: cedev-config: No such file or directory
make: * * * No targets. Stop
```

I did, in fact, extend my path var to the CEdev/bin files
```
...
export PATH=(home directory)/CEdev/bin:$PATH
```

and when I run ```ls``` in ~/CEdev/bin, this is what I get
```
cedev-config
convbin
convimg
ez80-link
cemu-autotester
convfont
ez80-clang
fasmg
```

I'm at a lost. Does anyone have ideas of what I could do?

**Comment by adriweb** [comment]
Did you re-start your terminal after having modified your shell configuration file (for the PATH modification)?
(You can also just `source` that file again from within an existing terminal)

**Comment by jvan1234** [comment]
I did. I also reset my computer and sourced it. It still doesn't work, giving the same result
Error:
```
make: cedev-config: No such file or directory
make: * * * No targets. Stop.
```
I know that file exists (I checked). Do I need to move it somewhere else (NOTE: This is not on the root level, could this effect anything)

**Comment by adriweb** [comment]
Well that's weird...
Does `cedev-config --makefile` work? And with the full path?

By the way did you build the toolchain yourself? Because we don't provide aarch64 binaries, so you'd have to get everything built on your own (including/especially the compiler).

**Comment by mateoconlechuga** [comment]
What is the exact line in your .bashrc? Are you sure it correct?

**Comment by jvan1234** [comment]
Oh, I didn't know ARM wasn't supported. I thought it was a universal package. I'll check the build instructions

Anyway, I wrote on line #115 on the .bashrc from my home directory, which is also near the end.

**Comment by adriweb** [comment]
Well you still haven't given us the actual full line, or answered my questions above :P

**Comment by jvan1234** [comment]
Building the toolchain now, just wanted to update!
adriweb, the makefile command gives me this error:
```bash: ./cedev-config: cannot execute binary file: Exec format error```
Also, here's the full line in my .bashrc
```export PATH=/(username)/home/CEdev/bin:$PATH```
(username) represents my username on the computer.

**Comment by adriweb** [comment]
Well the PATH export is wrong? `/(username)/home/...` It should be `/home/(username)/...` it's just a normal path to the folder.

And regarding the binary error, yes, that's normal since it's not built for your architecture.
