### ISSUE TITLE
int_least24_t and int_fast24_t

### ISSUE THREAD

**Issue by ZERICO2005** [CE-Programming/toolchain#503]
It would be nice to have `int_least24_t`, `int_fast24_t`, and 48bit equivalents available in `stdint.h`. While they would be useless on the eZ80 ti84ce, they would be helpful when porting code from the CE to Windows/Linux.

Some bugs arise from using `_BitInt(24)` as `int24_t` when porting code. Having `int_least24_t` and `int_fast24_t` would indicate that the code isn't dependent on the integer being exactly 24bits, which can reduce the amount of testing/validation needed.

**Comment by calc84maniac** [comment]
Well, there's kind of a problem because these aren't defined in any other stdint.h headers. So you would have to detect whether you're building for CE and typedef them if not, and at that point you can just typedef the CE versions yourself.

**Comment by mateoconlechuga** [comment]
Also I'd like to point out if you're porting something, then you're already modifying the code, so having things in a standard header doesn't help much, and might make things worse.
