### ISSUE TITLE
OS_TOK_STAT_F redefined

### ISSUE THREAD

**Issue by ZERICO2005** [CE-Programming/toolchain#504]
I noticed that `OS_TOK_STAT_F` is defined twice in `src/ce/include/ti/tokens.h`
```c
  848 | #define OS_TOK_STAT_F 0x26
 1403 | #define OS_TOK_STAT_F 0xAF
```
The latter seems out of place, ~~and I think it is supposed to be `OS_TOK_F`~~. It could be renamed to `OS_TOK_F_STAT` or etc since `OS_TOK_F` already exists as well

**Comment by adriweb** [comment]
Thanks!
