### ISSUE TITLE
sin() and cos() cause RAM reset

### ISSUE THREAD

**Issue by commandblockguy** [CE-Programming/toolchain#51]
GRAPHX4 will not run as a result of this
Replacing `sin(ANG);` and `cos(ANG)` with 1 in lines 58-59 allows the program to run

**Comment by MattWaltz** [comment]
This is because you are not uing the latest OS version fromTI, which includes these functions.

**Comment by MattWaltz** [comment]
@commandblockguy Alternatively, what do you think would be the best solution to fix this, out of curiosity?

**Comment by adriweb** [comment]
That said, I don't think there is any reason *not* to get on the latest OS :)

**Comment by commandblockguy** [comment]
I used the wrong ROM image for CEmu.
Maybe add a message if a program uses a function that requires the latest update, similarly to how a program stops when libraries are missing?

**Comment by commandblockguy** [comment]
Adding a note here (since I'm linking this issue somewhere) that there's now very much a reason not to get on the latest OS - 5.6 removes native code so definitely don't update to that, and there's no real need to upgrade past 5.3.0.

**Comment by adriweb** [comment]
(Unless you want/need Python stuff anyway)
