### ISSUE TITLE
Bring back x86_64 builds for the toolchain

### ISSUE THREAD

**Issue by Markos-Th09** [CE-Programming/toolchain#512]
Github recently switched its `macos-latest` action runners to apple silicon, meaning that the default build target is arm64. As there still people using intel macs, cross compilation to x86_64 should also be added to the build process

**Comment by adriweb** [comment]
Yeah, I'll take care of that.

**Comment by mateoconlechuga** [comment]
Release page updated: https://github.com/CE-Programming/toolchain/releases/tag/nightly
