### ISSUE TITLE
Makefile incorrectly escaped with wine 1.9.2 under Ubuntu 14.04

### ISSUE THREAD

**Issue by elfprince13** [CE-Programming/toolchain#6]
> [tdickerson@dickie] template $ wine ../../bin/make
CC: Unknown switch "..\INCLUDE\CE"
Linking...
WARNING (731) --> File "main.obj" is not found.
make: *** [template.hex] Error -1

**Comment by MateoConLechuga** [comment]
Um... What needs to be fixed here?

**Comment by MateoConLechuga** [comment]
Many thanks to jacobly, fixed with commit 2c76fa4
