### ISSUE TITLE
problem with kb_Data

### ISSUE THREAD

**Issue by ChaouiSama** [CE-Programming/toolchain#61]
Linking...
WARNING (724) --> Symbol _kb_Scan (obj\main.obj) is not defined.

**Comment by PeterTillema** [comment]
Did you include "keypadc" in your makefile, and included <keypadc.h>?

**Comment by adriweb** [comment]
(as in https://github.com/CE-Programming/toolchain/blob/master/examples/keypad_arrows/makefile#L20-L22)

**Comment by ChaouiSama** [comment]
effectively I had not included keypadc in the makefile I'm an idiot thank you guys
