### ISSUE TITLE
Why prgm_CleanUp

### ISSUE THREAD

**Issue by MattWaltz** [CE-Programming/toolchain#63]
Personally, I find having to do this ugly; as it should only be used at the end of a program. Please put it in the cstartup.asm file, and add a rule to the makefile to allow it in order to allow for a custom cleanup if need be.

**Comment by adriweb** [comment]
Looks like you did that with ba2111529cbfde0452cd074777b76aa7561e4c91

**Comment by MattWaltz** [comment]
Just need to add the function to replace it :)
