### ISSUE TITLE
Masking images for output

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/toolchain#68]
If would be nice if you can have a mask for an image, that not every pixel of the image will be converted/in the output.

**Comment by MattWaltz** [comment]
Wrong place for this ;) Also, Runer and I were talking and it doesn't really make sense; transparent sprites would solve most use cases for this.

**Comment by PeterTillema** [comment]
You said  yourself I had to post an issue though :P 
Anyway, I guess you don't get it, with transparent sprites you will still have a rectangular output, including the transparent pixels. My purpose was just to be able to get a non-rectangular output, that users can use their own, custom routine to display them (in my case, an isometric tile shape).
The idea might be to add an option to remove all the transparent pixels in the output or so, then you don't need any mask.
