### ISSUE TITLE
New hardware revisions break the toolchain's interrupt handling

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/toolchain#86]
More and more people are reporting issues on their recent CE (for instance on revisions I, manufactured at least in March 2017, but possibly earlier ones, after E)
For instance in Oiram, the keypad doesn't respond to keypresses anymore ; the toolchain's [keypad interrupt](https://github.com/CE-Programming/toolchain/tree/master/examples/keypad_interrupt) demo doesn't work either... , and the [interrupt counter](https://github.com/CE-Programming/toolchain/tree/master/examples/interrupt_counter) demo also freezes.

Needless to say, this breaks a whole lot of things, and it may be hard to do anything about it until we get our hands on a recent CE...

**Comment by adriweb** [comment]
(New report [on CW](http://codewalr.us/1586/58912), from yet another revision `I`, time time from April 2017)

**Comment by mateoconlechuga** [comment]
(New report on Cemetech, from May 2017, looks to be revision `I` but could possibly be also a revision `L`)

**Comment by mateoconlechuga** [comment]
https://usercontent.irccloud-cdn.com/file/CxICEL8d/DEM.8xp
https://usercontent.irccloud-cdn.com/file/NwiRvX5k/DEM2.8xp

These programs should be tested on revision I. The first one will print a string, and the second one will wait for you to press the [on] key. They are runable via `Asm(prgmDEM`. Please report back any findings. Thanks for your help!

**Comment by jacobly0** [comment]
Revision I calculators do not support im 2 which acts identically to im 0. Closing as can't fix, and deprecating custom interrupts in the toolchain.
