### ISSUE TITLE
Many errors after install

### ISSUE THREAD

**Issue by LemonJuiz** [CE-Programming/toolchain#90]
Following the on-screen instructions for the installer (just selecting a path, I chose the default `C:\CEdev`), I went to the [wiki](https://github.com/CE-Programming/toolchain/wiki/) and to the ["Building your first program"](https://github.com/CE-Programming/toolchain/wiki/Building-your-first-program) section. All I have done is clicked install from the v7.4.1 installer. Running make would produce this error:
```
C:\CEdev\examples\hello_world>make
makefile:33: /include/.makefile: No such file or directory
make: *** No rule to make target '/include/.makefile'.  Stop.
```

I was unsure of why `$(CEDEV)` was undefined from the makefile, so I manually went in to change that. Changing `$(CEDEV)/include/.makefile)` to `/c/CEdev/include/.makefile` produced this error:
```
C:\CEdev\examples\hello_world>make
%%I was unexpected at this time.
```
and would proceed to open up a new instance of `cmd.exe`. Other than edit the makefile, I have done nothing to anything in `C:\CEdev` so the cause of this error alludes me other then it was not setup correctly. Please look into!

**Comment by mateoconlechuga** [comment]
I think that we resolved this by determining that another `make` was interfering with the build process, and that installing on a user account did not propagate the value back as the installer requires an admin account. I'll be sure to fix this as soon as possible :)

**Comment by LemonJuiz** [comment]
Yes that was me :)
I'll leave this issue open as to let others who might have the same problem know it is being looked into.
For a temporary fix, make sure the account you are running from has the environment variable `CEDEV` set to your CEdev location. Type `where make` and make sure that the make program is in your CEdev path, otherwise change the filename `<CEdev location>\bin\make.exe` to something else like `make_ce`, then when you want to build type `make_ce` instead.

**Comment by mateoconlechuga** [comment]
I have pushed out a new release `7.4.2` which should address all of these issues. If you wouldn't mind testing it just to be sure; this issue can now be closed :)

https://github.com/CE-Programming/toolchain/releases/latest

**Comment by LemonJuiz** [comment]
I will try to do so shortly.
