### ISSUE TITLE
The makefile cannot handle Windows usernames with a space

### ISSUE THREAD

**Issue by UDXS** [CE-Programming/toolchain#97]
On Windows, the makefile is not prepared for spaces in names

Solution: surround variable names with quotation marks for the commands/locations

Workaround: clone it into the Public user or create a new user account with no spaces in it.

Thank You
-David M.

**Comment by mateoconlechuga** [comment]
Which makefile are you referring to? I believe a pull request may have broken this; I'll take a look.

**Comment by UDXS** [comment]
The one at the root, which we are told to run in the readme

**Comment by mateoconlechuga** [comment]
Do you really wish to build the toolchain itself for contributing reasons? Because it is nearly impossible to handle spaces across all OSes in makefiles, which is why cmake is usually a thing.

**Comment by mateoconlechuga** [comment]
Workaround: Use short path names on windows; or place in a path without spaces. Note that this is only really needed if you wish to contribute to the project; otherwise just use a release :)
