### ISSUE TITLE
Place switch inside the code will affect the success of the compilation

### ISSUE THREAD

**Issue by Xenoxis** [CE-Programming/toolchain#98]
I have a code in a function, with functions call on tice.h and/or graphx.h, and just after that, I have a char pointer declared and a int, like that : 
`os_EnableCursor();
    char *Str = CheckAlloc(calloc(1, MAX_STR_SIZE)), key;
    unsigned short xPos=0;`

That will never be compiled, because the compiler make somes errors, but, when i put os_EnableCursor(); after the pointer and unsigned short declaration, the code will compiling and work perfectly.
I think there is a bug in the compiler or an error in the libs for graphics calculator (but every functions in thoses lib make this bug)
Thanks you

**Comment by runer112** [comment]
Zilog's C compiler implements a pretty ancient version of the C standard that requires that all variable declarations in a scope be at the top of that scope. After the first statement in a scope that's not a variable declaration, in this case `os_EnableCursor();`, variable declarations are not allowed. As you discovered, you just need to put this statement after the variable declarations.

**Comment by Xenoxis** [comment]
And what about : `xPos = (xPos < 8) ? +1;`, is allowed ? What version of C standard is it ?

**Comment by adriweb** [comment]
You probably forgot a `:` if you wanted to write a short if.

**Comment by runer112** [comment]
As @adriweb suggested, the ternary operator requires three operands: the condition, the true case, and the false case. However, based on the plus sign, perhaps you're actually trying to increment xPos if it's less than 8? In that case, the ternary operator isn't really appropriate and you should use a normal if statement: `if (xPos < 8) xPos++;`.

I believe the C standard most closely implemented by the compiler is C89.

**Comment by Xenoxis** [comment]
Ok thanks, and there have any plans for upgrade to C99 or C11 ?

**Comment by runer112** [comment]
@jacobly0 has been working on an eZ80 (the CPU in the CE) target for llvm, which would allow using modern C and even C++ compilers like clang. However, it's still very much a work in progress and is not suitable for use yet. The project can be found here: https://github.com/jacobly0/llvm-z80
